Repository joyent/conch-api, pull requests merged in 2018-08, with the labels that each got.

#317 New logging framework and lots more log lines
  conch.conf.dist
  lib/Conch.pm
  lib/Conch/Controller/DB/HardwareProduct.pm
  lib/Conch/Controller/Datacenter.pm
  lib/Conch/Controller/DatacenterRack.pm
  lib/Conch/Controller/DatacenterRackLayout.pm
  lib/Conch/Controller/DatacenterRackRole.pm
  lib/Conch/Controller/DatacenterRoom.pm
  lib/Conch/Controller/Device.pm
  lib/Conch/Controller/DeviceLocation.pm
  lib/Conch/Controller/DeviceReport.pm
  lib/Conch/Controller/DeviceRoles.pm
  lib/Conch/Controller/DeviceServices.pm
  lib/Conch/Controller/DeviceSettings.pm
  lib/Conch/Controller/DeviceValidation.pm
  lib/Conch/Controller/HardwareProduct.pm
  lib/Conch/Controller/Login.pm
  lib/Conch/Controller/Relay.pm
  lib/Conch/Controller/User.pm
  lib/Conch/Controller/Validation.pm
  lib/Conch/Controller/ValidationPlan.pm
  lib/Conch/Controller/Workspace.pm
  lib/Conch/Controller/WorkspaceDevice.pm
  lib/Conch/Controller/WorkspaceProblem.pm
  lib/Conch/Controller/WorkspaceRack.pm
  lib/Conch/Controller/WorkspaceRelay.pm
  lib/Conch/Controller/WorkspaceRoom.pm
  lib/Conch/Controller/WorkspaceUser.pm
  lib/Conch/Controller/WorkspaceValidation.pm
  lib/Conch/Log.pm
  lib/Conch/Plugin/JsonValidator.pm
  lib/Conch/Plugin/Logging.pm
  lib/Conch/Role/MojoLog.pm
  lib/Conch/Time.pm
  lib/Conch/ValidationSystem.pm
  lib/Test/Conch/Datacenter.pm
  t/integration/02_hardware_product_profiles_loaded.t
  t/integration/03_zpool_profiles_loaded.t
  t/validation-system/01-load-validations.t
  t/validation-system/02-load-validation-plans.t
Labels: enhancement, refactor, tests

#318 features: new /user interfaces for adding, deleting users and resetting password
  json-schema/input.yaml
  json-schema/response.yaml
  lib/Conch/Command/create_user.pm
  lib/Conch/Controller/Login.pm
  lib/Conch/Controller/User.pm
  lib/Conch/Controller/WorkspaceUser.pm
  lib/Conch/DB/Result/UserAccount.pm
  lib/Conch/DB/ResultSet/UserAccount.pm
  lib/Conch/Mail.pm
  lib/Conch/Plugin/Mail.pm
  lib/Conch/Route.pm
  lib/Conch/Route/User.pm
  lib/Test/Conch.pm
  sql/migrations/0036-user_account-deactivate.sql
  sql/schema.sql
  t/integration/00_only_1_user_loaded.t
Labels: enhancement, refactor

#320 log exceptions in the dispatch logging and reintroduce stack frames to exception logging
  lib/Conch/Plugin/Logging.pm
Labels: enhancement

#321 fix: update user_account.last_login when user logs in
  Makefile
  cpanfile
  cpanfile.snapshot
  lib/Conch/Controller/Login.pm
  lib/Conch/DB/InflateColumn/Time.pm
  lib/Conch/DB/Result/Datacenter.pm
  lib/Conch/DB/Result/DatacenterRack.pm
  lib/Conch/DB/Result/DatacenterRackLayout.pm
  lib/Conch/DB/Result/DatacenterRackRole.pm
  lib/Conch/DB/Result/DatacenterRoom.pm
  lib/Conch/DB/Result/Device.pm
  lib/Conch/DB/Result/DeviceDisk.pm
  lib/Conch/DB/Result/DeviceEnvironment.pm
  lib/Conch/DB/Result/DeviceLocation.pm
  lib/Conch/DB/Result/DeviceLog.pm
  lib/Conch/DB/Result/DeviceMemory.pm
  lib/Conch/DB/Result/DeviceNeighbor.pm
  lib/Conch/DB/Result/DeviceNic.pm
  lib/Conch/DB/Result/DeviceNicState.pm
  lib/Conch/DB/Result/DeviceRelayConnection.pm
  lib/Conch/DB/Result/DeviceReport.pm
  lib/Conch/DB/Result/DeviceRole.pm
  lib/Conch/DB/Result/DeviceRoleService.pm
  lib/Conch/DB/Result/DeviceService.pm
  lib/Conch/DB/Result/DeviceSetting.pm
  lib/Conch/DB/Result/DeviceSpec.pm
  lib/Conch/DB/Result/DeviceValidate.pm
  lib/Conch/DB/Result/DeviceValidateCriteria.pm
  lib/Conch/DB/Result/HardwareProduct.pm
  lib/Conch/DB/Result/HardwareProductProfile.pm
  lib/Conch/DB/Result/HardwareProfileSetting.pm
  lib/Conch/DB/Result/HardwareVendor.pm
  lib/Conch/DB/Result/Migration.pm
  lib/Conch/DB/Result/Relay.pm
  lib/Conch/DB/Result/Role.pm
  lib/Conch/DB/Result/UserAccount.pm
  lib/Conch/DB/Result/UserRelayConnection.pm
  lib/Conch/DB/Result/UserSessionToken.pm
  lib/Conch/DB/Result/UserSetting.pm
  lib/Conch/DB/Result/UserWorkspaceRole.pm
  lib/Conch/DB/Result/Validation.pm
  lib/Conch/DB/Result/ValidationPlan.pm
  lib/Conch/DB/Result/ValidationPlanMember.pm
  lib/Conch/DB/Result/ValidationResult.pm
  lib/Conch/DB/Result/ValidationState.pm
  lib/Conch/DB/Result/ValidationStateMember.pm
  lib/Conch/DB/Result/Workspace.pm
  lib/Conch/DB/Result/WorkspaceDatacenterRack.pm
  lib/Conch/DB/Result/WorkspaceDatacenterRoom.pm
  lib/Conch/DB/Result/ZpoolProfile.pm
  lib/Conch/Time.pm
  schema.conf
  t/conch_time.t
  t/integration/00_only_1_user_loaded.t
Labels: enhancement

#324 DIMM map validation
  lib/Conch/Validation.pm
  lib/Conch/Validation/DimmMap.pm
  t/validations/dimm_map_v1.t
Labels: enhancement

#325 amendment for PR#319 changes: delete entries from related tables before deleting users
  sql/migrations/0037-user-account-email-citext.sql
Labels: bug

#326 add a makefile target "make test_loud" that turns on mojo logging during a non-verbose test run
  Makefile
Labels: enhancement, tests

#327 fix bad invocations of send_mail_*
  lib/Conch.pm
  lib/Conch/Controller/Login.pm
  lib/Conch/Controller/User.pm
  lib/Conch/Controller/WorkspaceUser.pm
  lib/Conch/Plugin/Mail.pm
Labels: bug

#330 new test for multiple db connections in a test
  lib/Test/Conch.pm
  t/test-conch.t
Labels: bug, enhancement

#328 First round of cleanups and simplifications on the Validation system
  json-schema/input.yaml
  lib/Conch/Controller/DeviceReport.pm
  lib/Conch/Controller/DeviceValidation.pm
  lib/Conch/Controller/ValidationPlan.pm
  lib/Conch/Model/Validation.pm
  lib/Conch/Model/ValidationPlan.pm
  lib/Conch/Model/ValidationState.pm
  lib/Conch/Validation.pm
  lib/Conch/Validation/BiosFirmwareVersion.pm
  lib/Conch/Validation/CpuCount.pm
  lib/Conch/Validation/CpuTemperature.pm
  lib/Conch/Validation/DeviceProductName.pm
  lib/Conch/Validation/DimmCount.pm
  lib/Conch/Validation/RamTotal.pm
  lib/Conch/Validation/SwitchPeers.pm
  lib/Conch/ValidationSystem.pm
  lib/Test/Conch.pm
  lib/Test/Conch/Datacenter.pm
  lib/Test/Conch/Validation.pm
  t/integration/02_hardware_product_profiles_loaded.t
  t/integration/03_zpool_profiles_loaded.t
  t/integration/04_test_datacenter_loaded.t
  t/integration/05_response_schema.t
  t/model/Validation.t
  t/model/ValidationPlan.t
  t/model/ValidationState.t
  t/validation-system/01-load-validations.t
  t/validation-system/02-load-validation-plans.t
  t/validations/00_base_class.t
  t/validations/bios_firmware_version_v1.t
  t/validations/cpu_count_v1.t
  t/validations/cpu_temperature_v1.t
  t/validations/device_product_name_v1.t
  t/validations/dimm_count_v1.t
  t/validations/dimm_map_v1.t
  t/validations/disk_smart_status_v1.t
  t/validations/disk_temperature_v1.t
  t/validations/links_up_v1.t
  t/validations/ram_total_v1.t
  t/validations/sas_hdd_num_v1.t
  t/validations/sas_ssd_num_v1.t
  t/validations/slog_slot_v1.t
  t/validations/switch_peers_v1.t
  t/validations/usb_hdd_num_v1.t
Labels: enhancement, refactor

#329 When resetting a user's password, force them to change it
  lib/Conch.pm
  lib/Conch/Controller/Login.pm
  lib/Conch/Controller/User.pm
  lib/Conch/DB/Result/UserAccount.pm
  lib/Conch/Mail.pm
  lib/Conch/Route/User.pm
  lib/Test/Conch.pm
  sql/migrations/0038-force-password-change.sql
  sql/schema.sql
  t/integration/00_only_1_user_loaded.t
Labels: bug, enhancement

#331 ether's weekly cleanup branch
  .mailmap
  Makefile
  cpanfile
  cpanfile.snapshot
  lib/Conch.pm
  lib/Conch/Command/create_user.pm
  lib/Conch/Controller/DeviceReport.pm
  lib/Conch/Controller/Login.pm
  lib/Conch/Controller/User.pm
  lib/Conch/Controller/WorkspaceProblem.pm
  lib/Conch/Controller/WorkspaceUser.pm
  lib/Conch/Legacy/Control/DeviceReport.pm
  lib/Conch/Legacy/Control/Problem.pm
  lib/Conch/Mail.pm
  lib/Conch/Plugin/Features.pm
  lib/Conch/Plugin/Logging.pm
  lib/Conch/Plugin/Mail.pm
  lib/Conch/Role/MojoLog.pm
  lib/Conch/Route.pm
  lib/Test/Conch.pm
  lib/Test/Conch/Datacenter.pm
  lib/Test/Conch/Validation.pm
  schema-loader.yaml
  schema.conf
  t/conch_time.t
  t/integration/00_only_1_user_loaded.t
  t/validations/00_base_class.t
Labels: refactor

#333 more misc background refactoring
  Makefile
  cpanfile
  cpanfile.snapshot
  lib/Conch/Controller/Device.pm
  lib/Conch/DB/Result/RelayDevices.pm
  lib/Conch/Model/Device.pm
  lib/Conch/Model/DeviceLocation.pm
  lib/Conch/Model/HardwareProduct.pm
  lib/Conch/Model/Workspace.pm
  lib/Conch/Model/WorkspaceRack.pm
  lib/Conch/Model/WorkspaceRelay.pm
  lib/Conch/Model/WorkspaceRole.pm
  lib/Conch/Model/WorkspaceRoom.pm
  lib/Conch/Model/WorkspaceUser.pm
  lib/Test/Conch.pm
Labels: refactor

#335 move role.name to user_workspace_role.role
  dev/sql/01-dev-user.sql
  docs/validation/Guide.md
  lib/Conch/Class/Workspace.pm
  lib/Conch/Class/WorkspaceRole.pm
  lib/Conch/Controller/Workspace.pm
  lib/Conch/Controller/WorkspaceRack.pm
  lib/Conch/Controller/WorkspaceRoom.pm
  lib/Conch/Controller/WorkspaceUser.pm
  lib/Conch/DB/Result/Role.pm
  lib/Conch/DB/Result/UserWorkspaceRole.pm
  lib/Conch/Model/Workspace.pm
  lib/Conch/Model/WorkspaceRole.pm
  lib/Conch/Model/WorkspaceUser.pm
  lib/Conch/Models.pm
  lib/Conch/Plugin/AuthHelpers.pm
  lib/Test/ConchTmpDB.pm
  sql/migrations/0039-remove-role-table.sql
  sql/schema.sql
  t/class/WorkspaceRole.t
  t/integration/00_only_1_user_loaded.t
  t/integration/04_test_datacenter_loaded.t
  t/model/Device.t
  t/model/Workspace.t
  t/model/WorkspaceRole.t
  t/model/WorkspaceUser.t
Labels: breaking, enhancement, refactor

#334 Cleanups around json validation and validation logs
  lib/Conch/Plugin/JsonValidator.pm
  lib/Conch/Validation.pm
  t/model/Validation.t
  t/validations/00_base_class.t
Labels: refactor

#336 allow for skipping modules in pod coverage tests
  t/pod-coverage.t
Labels: tests

#341 new endpoint: GET /user/<target user>
  lib/Conch/Controller/User.pm
  lib/Conch/DB/Result/UserAccount.pm
  lib/Conch/Route/User.pm
  t/integration/00_only_1_user_loaded.t
Labels: enhancement

#342 remove remaining views
  lib/Conch/Controller/WorkspaceProblem.pm
  lib/Conch/DB/Result/Device.pm
  lib/Conch/DB/Result/DeviceRelayConnection.pm
  lib/Conch/DB/Result/LatestDeviceReport.pm
  lib/Conch/DB/Result/UnlocatedUserRelayDevices.pm
  lib/Conch/DB/Result/UserRelayConnection.pm
  lib/Conch/DB/Result/WorkspaceDevices.pm
  t/integration/04_test_datacenter_loaded.t
Labels: refactor

#343 pass the user's name into the changed_user_password email
  lib/Conch/Controller/User.pm
Labels: bug

#350 fix db column and relationship names
  lib/Conch/Controller/DB/HardwareProduct.pm
  lib/Conch/Controller/DeviceReport.pm
  lib/Conch/DB/Result/Datacenter.pm
  lib/Conch/DB/Result/DatacenterRackLayout.pm
  lib/Conch/DB/Result/DatacenterRoom.pm
  lib/Conch/DB/Result/DeviceNeighbor.pm
  lib/Conch/DB/Result/DeviceRole.pm
  lib/Conch/DB/Result/DeviceRoleService.pm
  lib/Conch/DB/Result/DeviceService.pm
  lib/Conch/DB/Result/DeviceSpec.pm
  lib/Conch/DB/Result/DeviceValidateCriteria.pm
  lib/Conch/DB/Result/HardwareProduct.pm
  lib/Conch/DB/Result/HardwareProductProfile.pm
  lib/Conch/DB/Result/HardwareProfileSetting.pm
  lib/Conch/DB/Result/HardwareVendor.pm
  lib/Conch/Model/DatacenterRackLayout.pm
  lib/Conch/Model/DatacenterRoom.pm
  lib/Conch/Model/DeviceLocation.pm
  lib/Conch/Model/DeviceRole.pm
  lib/Conch/Model/HardwareProduct.pm
  lib/Conch/Model/WorkspaceRack.pm
  schema-loader.yaml
  sql/migrations/0041-rename-devicerole-columns.sql
  sql/schema.sql
  sql/test/00-hardware.sql
  sql/test/01-hardware-profiles.sql
  sql/test/02-zpool-profiles.sql
  sql/test/03-test-datacenter.sql
  t/model/DatacenterRack.t
  t/model/DatacenterRackLayout.t
  t/model/Device.t
  t/model/DeviceReport.t
  t/model/DeviceRole.t
  t/model/DeviceSettings.t
  t/model/HardwareProduct.t
  t/model/Relay.t
  t/model/Validation.t
  t/model/ValidationPlan.t
  t/model/ValidationResult.t
  t/model/ValidationState.t
  t/pod-coverage.t
Labels: refactor

#352 Adds a fallback to legacy product name in DeviceReport#process and removes two json schema requirements for device reports
  json-schema/input.yaml
  lib/Conch/Controller/DeviceReport.pm
  lib/Conch/Legacy/Control/DeviceReport.pm
  t/integration/00_only_1_user_loaded.t
  t/integration/01_hardware_products_loaded.t
Labels: enhancement, refactor, tests

#353 Cleans up DeviceReport#process, introducing a legacy product name lookup along the way.
  json-schema/input.yaml
  lib/Conch/Controller/DeviceReport.pm
  lib/Conch/Route/Device.pm
  t/integration/00_only_1_user_loaded.t
  t/integration/01_hardware_products_loaded.t
Labels: enhancement, refactor, tests

#354 Cleans up DeviceReport#process, introducing a legacy product name lookup along the way. (2.16 variant)
  json-schema/input.yaml
  lib/Conch/Controller/DeviceReport.pm
  lib/Conch/Route/Device.pm
  t/integration/00_only_1_user_loaded.t
  t/integration/01_hardware_products_loaded.t
Labels: enhancement, refactor, tests

#363 remove the /feedback route that did nothing useful
  lib/Conch/Route.pm
  t/integration/06_secured_endpoints.t
Labels: refactor

#364 remove the build.validated workaround now that the relay/rebooter fix has been in production for a while.
  lib/Conch/Controller/DeviceSettings.pm
  t/integration/04_test_datacenter_loaded.t
Labels: refactor

#365 clean up all route definitions
  lib/Conch/Controller/DB/HardwareProduct.pm
  lib/Conch/Controller/Datacenter.pm
  lib/Conch/Controller/DatacenterRack.pm
  lib/Conch/Controller/DatacenterRackLayout.pm
  lib/Conch/Controller/DatacenterRackRole.pm
  lib/Conch/Controller/DatacenterRoom.pm
  lib/Conch/Controller/Device.pm
  lib/Conch/Controller/DeviceReport.pm
  lib/Conch/Controller/DeviceRoles.pm
  lib/Conch/Controller/DeviceServices.pm
  lib/Conch/Controller/DeviceValidation.pm
  lib/Conch/Controller/HardwareProduct.pm
  lib/Conch/Controller/ValidationPlan.pm
  lib/Conch/Route.pm
  lib/Conch/Route/DB/HardwareProduct.pm
  lib/Conch/Route/Datacenter.pm
  lib/Conch/Route/Device.pm
  lib/Conch/Route/HardwareProduct.pm
  lib/Conch/Route/Relay.pm
  lib/Conch/Route/User.pm
  lib/Conch/Route/Validation.pm
  lib/Conch/Route/Workspace.pm
Labels: refactor

#367 new GET /device?<thing>=<value> endpoint
  lib/Conch/Controller/Device.pm
  lib/Conch/Route/Device.pm
  t/integration/04_test_datacenter_loaded.t
Labels: api, enhancement

#393 new /hardware_vendor endpoints
  json-schema/response.yaml
  lib/Conch/Controller/HardwareVendor.pm
  lib/Conch/DB/Result/HardwareVendor.pm
  lib/Conch/Route.pm
  lib/Conch/Route/HardwareVendor.pm
  t/integration/02_hardware_product_profiles_loaded.t
Labels: api, enhancement, needs-shell

#395 strip device models
  lib/Conch/Class/DeviceDetailed.pm
  lib/Conch/Controller/Device.pm
  lib/Conch/Controller/DeviceLocation.pm
  lib/Conch/Controller/DeviceReport.pm
  lib/Conch/Controller/DeviceRoles.pm
  lib/Conch/Controller/DeviceServices.pm
  lib/Conch/Controller/DeviceSettings.pm
  lib/Conch/Controller/DeviceValidation.pm
  lib/Conch/Controller/Workspace.pm
  lib/Conch/Controller/WorkspaceProblem.pm
  lib/Conch/DB/Result/Device.pm
  lib/Conch/DB/Result/DeviceRole.pm
  lib/Conch/DB/ResultSet/DeviceSetting.pm
  lib/Conch/DB/ResultSet/UserAccount.pm
  lib/Conch/DB/ResultSet/Workspace.pm
  lib/Conch/Model/Device.pm
  lib/Conch/Model/DeviceReport.pm
  lib/Conch/Model/DeviceRole.pm
  lib/Conch/Model/DeviceService.pm
  lib/Conch/Model/DeviceSettings.pm
  lib/Conch/Model/Validation.pm
  lib/Conch/Model/ValidationPlan.pm
  lib/Conch/Models.pm
  t/integration/04_test_datacenter_loaded.t
  t/integration/05_response_schema.t
  t/model/Device.t
  t/model/DeviceReport.t
  t/model/DeviceRole.t
  t/model/DeviceService.t
  t/model/DeviceSettings.t
Labels: refactor

#403 fix postgres + perl consuming memory on the device_validates query
  lib/Conch/Controller/Device.pm
Labels: bug

#402 After deleting a user, that email address cannot be reused in a new user.
  lib/Conch/Controller/User.pm
  lib/Conch/DB/Result/UserAccount.pm
  sql/migrations/0042-user_account-email-uniqueness.sql
  sql/schema.sql
  t/integration/00_only_1_user_loaded.t
Labels: bug

#404 burn device_validate, device_validate_criteria tables, phase 1
  json-schema/response.yaml
  lib/Conch/Controller/Device.pm
  lib/Conch/Controller/WorkspaceProblem.pm
  report/README.md
  report/bin/device_validation_result_dump.pl
  report/manta_jobs/time_to_earliest_remediation/filter_redundant_results.js
  report/manta_jobs/time_to_earliest_remediation/job.json
  report/manta_jobs/time_to_earliest_remediation/reduce_first_failure_and_pass.js
Labels: breaking, refactor

#405 new device interface routes
  cpanfile
  cpanfile.snapshot
  json-schema/response.yaml
  lib/Conch/Controller/Device.pm
  lib/Conch/Controller/DeviceInterface.pm
  lib/Conch/Controller/DeviceReport.pm
  lib/Conch/DB/Result/DeviceNic.pm
  lib/Conch/DB/Result/DeviceNicState.pm
  lib/Conch/Route/Device.pm
  sql/migrations/0043-drop-user_account_bak_v2_15.sql
  sql/migrations/0044-collapse-device_nic_state.sql
  sql/schema.sql
  t/integration/04_test_datacenter_loaded.t
  t/integration/crud/devices.t
Labels: api, enhancement
