Repository joyent/conch-api, pull requests merged in 2018-03, with the labels that each got.

#180 feat: add Conch::Time->now()
  Conch/cpanfile
  Conch/lib/Conch/Time.pm
  Conch/t/conch_time.t
Labels: api, enhancement

#185 ui: update moment.js to 2.21 to fix a security issue
  Conch/ui/package-lock.json
  Conch/ui/package.json
Labels: security, ui

#186 Update JS dependencies, switch fully to Yarn
  .gitignore
  Conch/Makefile
  Conch/ui/package-lock.json
  Conch/ui/package.json
  Conch/ui/webpack.config.js
  Conch/ui/yarn.lock
Labels: enhancement, ui

#188 fix: missed a pair of Model::User calls in invite() when removing the now-unnecessary db handles
  Conch/lib/Conch/Controller/WorkspaceUser.pm
Labels: api, bug

#189 docs: reinstate the openapi docs.
  Conch/Makefile
  Conch/docs/conch-api/index.html
  Conch/docs/conch-api/index.js
  Conch/docs/conch-api/openapi-spec.yaml
  Conch/docs/conch-api/package-lock.json
  Conch/docs/conch-api/package.json
  Conch/docs/conch-api/yarn.lock
  Conch/lib/Conch/Route.pm
Labels: api, docs

#192 Revert integration of Time::Moment, which fails to build on SmartOS
  Conch/cpanfile
  Conch/cpanfile.snapshot
  Conch/lib/Conch/Time.pm
  Conch/t/conch_time.t
Labels: bug

#193 fix: fix invite user endpoint
  Conch/cpanfile.snapshot
  Conch/lib/Conch/Controller/WorkspaceUser.pm
Labels: bug

#196 Reintroduce Time::Moment now that it builds on SmartOS
  Conch/cpanfile
  Conch/cpanfile.snapshot
  Conch/lib/Conch/Time.pm
  Conch/t/conch_time.t
Labels: api

#197 build: travis integration
  .travis.yml
Labels: build

#201 refactor: in Conch::Time, use the lenient parsing of Time::Moment rather than our own custom parser
  Conch/lib/Conch/Time.pm
  Conch/t/conch_time.t
Labels: api

#210 test: add a method to Test::ConchTmp::DB to spin up a database using all sql files in sql/test
  Conch/lib/Test/ConchTmpDB.pm
Labels: tests

#208 build: makefile target to run a dev instance in morbo
  Conch/Makefile
Labels: build

#212 build: let travis operate on branches other than master
  .travis.yml
Labels: build

#151 Preflight Orchestration System: CRUD API
  Conch/conch.conf.dist
  Conch/cpanfile
  Conch/cpanfile.snapshot
  Conch/json-schema/v1.yaml
  Conch/lib/Conch.pm
  Conch/lib/Conch/Controller/Orc/WorkflowSteps.pm
  Conch/lib/Conch/Controller/Orc/Workflows.pm
  Conch/lib/Conch/Orc.pm
  Conch/lib/Conch/Orc/Workflow.pm
  Conch/lib/Conch/Orc/Workflow/Status.pm
  Conch/lib/Conch/Orc/Workflow/Step.pm
  Conch/lib/Conch/Orc/Workflow/Step/Status.pm
  Conch/lib/Conch/Role/But.pm
  Conch/lib/Conch/Route.pm
  Conch/lib/Conch/Route/Orc.pm
  Conch/lib/Conch/Time.pm
  Conch/lib/Test/ConchTmpDB.pm
  Conch/t/integration/orc/build.t
  Conch/t/integration/orc/workflows.t
  Conch/t/orc/00-load.t
  Conch/t/orc/01-workflow.t
  Conch/t/orc/02-workflow_status.t
  Conch/t/orc/03-workflow_step.t
  Conch/t/orc/04-workflow_step_status.t
  Conch/t/orc/05-workflow_steps.t
  sql/migrations/0023-orchestration.sql
Labels: api

#216 Put auditing and rollbar into the feature flags system
  Conch/conch.conf.dist
  Conch/lib/Conch.pm
Labels: api, enhancement

#218 fix: in before_render, only try to send the exception to rollbar if the feature is active
  Conch/lib/Conch.pm
Labels: api, bug
