Repository joyent/conch-api, pull requests merged in 2018-11, with the labels that each got.

#525 put the nytprof plugin behind a feature flag
  conch.conf.dist
  lib/Conch.pm
Labels: tests

#526 add a new feature flag that caused the API to log to stderr, not the log directory
  conch.conf.dist
  lib/Conch/Plugin/Logging.pm
  lib/Conch/Role/MojoLog.pm
Labels: enhancement

#527 fix oversight: this permission check should have become $user->is_admin
  lib/Conch/Controller/Workspace.pm
Labels: bug

#523 extend POST /hardware_product/(:id)? to create or update a hardware_product_profile
  Dockerfile
  Dockerfile.dev
  cpanfile
  cpanfile.snapshot
  json-schema/input.yaml
  lib/Conch.pm
  lib/Conch/Controller/HardwareProduct.pm
  lib/Conch/Plugin/Database.pm
  lib/Conch/Plugin/JsonValidator.pm
  sql/migrations/0065-zpool_profile-name-unique.sql
  sql/schema.sql
  t/database.t
  t/integration/crud/hardware_product.t
Labels: api, database, enhancement, needs-shell, needs-ui

#529 add request id to response headers
  lib/Conch.pm
  t/integration/00_only_1_user_loaded.t
Labels: api, enhancement

#534 properly handle wide passwords in forms and scripts
  cpanfile
  cpanfile.snapshot
  lib/Conch/Command/create_user.pm
  lib/Conch/DB/Result/UserAccount.pm
  t/integration/00_only_1_user_loaded.t
Labels: bug

#535 ensure that postgres connects using client_encoding = UTF-8
  conch.conf.dist
  lib/Conch/Plugin/Database.pm
  lib/Test/ConchTmpDB.pm
Labels: database

#533 Always save device reports, flagging them as 'invalid' if necessary.
  json-schema/response.yaml
  lib/Conch/Controller/Device.pm
  lib/Conch/Controller/DeviceReport.pm
  lib/Conch/DB/Result/DeviceReport.pm
  lib/Conch/DB/ResultSet.pm
  lib/Conch/DB/ResultSet/Device.pm
  sql/migrations/0066-invalid-device_reports.sql
  sql/schema.sql
  t/integration/04_test_datacenter_loaded.t
  t/integration/resource/error-device-report.json
Labels: database, enhancement, needs-shell, needs-ui

#531 gracefully handle the lack of a git repository
  cpanfile
  lib/Conch/Plugin/GitVersion.pm
Labels: api, bug

#538 a collection of small fixes
  json-schema/input.yaml
  json-schema/response.yaml
  lib/Conch.pm
  lib/Conch/Controller/DeviceReport.pm
  lib/Conch/Controller/User.pm
  lib/Conch/DB/ResultSet/Workspace.pm
  lib/Conch/Plugin/Logging.pm
  lib/Conch/Plugin/Rollbar.pm
  lib/Conch/Route/Validation.pm
  lib/Conch/Route/Workspace.pm
Labels: api, bug

#542 support workspace name in place of id in workspace endpoints
  lib/Conch/Controller/Workspace.pm
  lib/Conch/Plugin/AuthHelpers.pm
  lib/Conch/Route/Workspace.pm
  t/integration/00_only_1_user_loaded.t
Labels: api, enhancement

#539 More improvements to the docker environment
  Dockerfile
  Dockerfile.dev
  docker/buildbot-prerelease.bash
  docker/buildbot-release.bash
  docker/builder.sh
  docker/dev_test.bash
  docker/remove_old_images.bash
Labels: build

#544 do not expose parent workspace ids to users who lack the auth to see them
  lib/Conch/Controller/Workspace.pm
  t/integration/00_only_1_user_loaded.t
Labels: api, enhancement

#548 add disk info to GET /device/:id
  json-schema/response.yaml
  lib/Conch/Controller/Device.pm
  lib/Conch/DB/Result/DeviceDisk.pm
  t/integration/04_test_datacenter_loaded.t
Labels: api, enhancement

#549 refactor test scaffolding
  cpanfile
  cpanfile.snapshot
  lib/Test/Conch.pm
  lib/Test/Conch/Datacenter.pm
  lib/Test/Conch/Fixtures.pm
  lib/Test/ConchTmpDB.pm
  sql/test/00-hardware.sql
  sql/test/01-hardware-profiles.sql
  sql/test/02-zpool-profiles.sql
  sql/test/03-test-datacenter.sql
  sql/test/README
  t/01-compile.t
  t/conch_time.t
  t/database.t
  t/integration/00_only_1_user_loaded.t
  t/integration/01_hardware_products_loaded.t
  t/integration/02_hardware_product_profiles_loaded.t
  t/integration/03_zpool_profiles_loaded.t
  t/integration/04_test_datacenter_loaded.t
  t/integration/crud/datacenter.t
  t/integration/crud/devices.t
  t/integration/crud/hardware_product.t
  t/integration/crud/rack_layouts.t
  t/integration/crud/rack_roles.t
  t/integration/crud/racks.t
  t/integration/crud/unsecured-endpoints.t
  t/model/Validation.t
  t/test-conch.t
Labels: refactor, tests

#554 no longer mutate the validation database entries on startup
  cpanfile
  cpanfile.snapshot
  lib/Conch.pm
  lib/Conch/Command/update_validations.pm
  lib/Conch/Model/Validation.pm
  lib/Conch/Plugin/Database.pm
  lib/Conch/UUID.pm
  lib/Conch/Validation/DeviceProductName.pm
  lib/Conch/ValidationSystem.pm
  lib/Test/Conch.pm
  t/conch_uuid.t
  t/integration/02_hardware_product_profiles_loaded.t
  t/integration/03_zpool_profiles_loaded.t
  t/integration/04_test_datacenter_loaded.t
  t/integration/crud/devices.t
  t/lib/Conch/Validation/Broken.pm
  t/lib/Conch/Validation/Empty.pm
  t/lib/Conch/Validation/WrongDescription.pm
  t/lib/Conch/Validation/WrongName.pm
  t/lib/Conch/Validation/WrongParentage.pm
  t/lib/Conch/Validation/WrongVersion.pm
  t/model/Validation.t
  t/model/ValidationPlan.t
  t/model/ValidationState.t
  t/validation-system/00-load.t
  t/validation-system/01-load-validations.t
  t/validation-system/check_validations.t
  t/validation-system/load_validations.t
Labels: enhancement, validation

#556 check for occupancy conflicts when updating rack layouts
  lib/Conch/Command/check_layouts.pm
  lib/Conch/Controller/DatacenterRackLayout.pm
  lib/Conch/DB/ResultSet/DatacenterRack.pm
  t/integration/crud/rack_layouts.t
Labels: bug, build, enhancement

#557 fix argument handling for commands
  lib/Conch/Command/check_layouts.pm
  lib/Conch/Command/clean_permissions.pm
  lib/Conch/Command/create_user.pm
  lib/Conch/Command/update_validation_states.pm
  lib/Conch/Command/update_validations.pm
  lib/Conch/Command/workspaces.pm
Labels: bug
