Repository joyent/conch-api, pull requests merged in 2018-04, with the labels that each got.

#220 feat: add Conch::Plugin::JsonValidator, allowing controllers to optionally validate input and output.
  Conch/json-schema/input.yaml
  Conch/lib/Conch.pm
  Conch/lib/Conch/Controller/Orc/Workflows.pm
  Conch/lib/Conch/Plugin/JsonValidator.pm
Labels: api, enhancement

#219 Device Roles and Services: defining the intended usage of a device
  Conch/cpanfile
  Conch/cpanfile.snapshot
  Conch/json-schema/v1.yaml
  Conch/lib/Conch/Controller/Device.pm
  Conch/lib/Conch/Controller/DeviceRoles.pm
  Conch/lib/Conch/Controller/DeviceServices.pm
  Conch/lib/Conch/Model/Device.pm
  Conch/lib/Conch/Model/DeviceRole.pm
  Conch/lib/Conch/Model/DeviceService.pm
  Conch/lib/Conch/Models.pm
  Conch/lib/Conch/Role/Timestamps.pm
  Conch/lib/Conch/Route/Device.pm
  Conch/t/integration/04_test_datacenter_loaded.t
  Conch/t/integration/05_v1_schema.t
  Conch/t/model/DeviceRole.t
  Conch/t/model/DeviceService.t
  sql/migrations/0024-device-roles.sql
Labels: api, enhancement

#222 Execute Validation Plans in Device Ingest
  Conch/conch.conf.dist
  Conch/cpanfile
  Conch/cpanfile.snapshot
  Conch/lib/Conch.pm
  Conch/lib/Conch/Controller/DeviceReport.pm
  Conch/lib/Conch/Minion.pm
  Conch/lib/Conch/Model/Validation.pm
  Conch/lib/Conch/Model/ValidationPlan.pm
  Conch/lib/Conch/Model/ValidationResult.pm
  Conch/lib/Conch/Model/ValidationState.pm
  Conch/lib/Conch/Validation.pm
  Conch/lib/Conch/Validation/LinksUp.pm
  Conch/lib/Conch/Validation/SasHddNum.pm
  Conch/lib/Conch/Validation/SasSsdNum.pm
  Conch/lib/Conch/Validation/SlogSlot.pm
  Conch/lib/Conch/ValidationError.pm
  Conch/lib/Conch/ValidationSystem.pm
  Conch/t/model/Validation.t
  Conch/t/model/ValidationPlan.t
  Conch/t/model/ValidationResult.t
  Conch/t/model/ValidationState.t
  Conch/t/validation-system/01-load-validations.t
  Conch/t/validation-system/01-run-validation-plan.t
  Conch/t/validation-system/02-load-validation-plans.t
  Conch/t/validation-system/03-start-tasks.t
  Conch/t/validations/00_base_class.t
  sql/migrations/0026-validation-results.sql
Labels: api, enhancement

#221 feat: Orc Lifecycles, an ordered list of workflows, bound to a device role
  Conch/json-schema/input.yaml
  Conch/json-schema/v1.yaml
  Conch/lib/Conch/Controller/Orc/Lifecycles.pm
  Conch/lib/Conch/Orc.pm
  Conch/lib/Conch/Orc/Lifecycle.pm
  Conch/lib/Conch/Orc/Workflow.pm
  Conch/lib/Conch/Route/Orc.pm
  Conch/lib/Conch/Time.pm
  Conch/t/integration/orc/workflows.t
  Conch/t/orc/00-load.t
  Conch/t/orc/06-lifecycle.t
  sql/migrations/0025-orc-lifecycles.sql
Labels: api, enhancement

#224 feat: move Conch::Orc over to Moo::Role::ToJSON
  Conch/lib/Conch/Controller/Orc/WorkflowSteps.pm
  Conch/lib/Conch/Controller/Orc/Workflows.pm
  Conch/lib/Conch/Orc/Workflow.pm
  Conch/lib/Conch/Orc/Workflow/Status.pm
  Conch/lib/Conch/Orc/Workflow/Step.pm
  Conch/lib/Conch/Orc/Workflow/Step/Status.pm
  Conch/t/orc/01-workflow.t
  Conch/t/orc/02-workflow_status.t
  Conch/t/orc/03-workflow_step.t
  Conch/t/orc/04-workflow_step_status.t
Labels: api, enhancement

#225 refactor: move Orc: to Role::Timestamps
  Conch/lib/Conch/Orc/Workflow.pm
  Conch/lib/Conch/Orc/Workflow/Step.pm
  Conch/lib/Conch/Orc/Workflow/Step/Status.pm
Labels: api, refactor

#226 feat: Endpoints for getting validation states with results
  Conch/json-schema/v1.yaml
  Conch/lib/Conch/Controller/DeviceValidation.pm
  Conch/lib/Conch/Controller/Validation.pm
  Conch/lib/Conch/Controller/ValidationPlan.pm
  Conch/lib/Conch/Controller/WorkspaceValidation.pm
  Conch/lib/Conch/Model/Validation.pm
  Conch/lib/Conch/Model/ValidationPlan.pm
  Conch/lib/Conch/Model/ValidationResult.pm
  Conch/lib/Conch/Model/ValidationState.pm
  Conch/lib/Conch/Models.pm
  Conch/lib/Conch/Route/Device.pm
  Conch/lib/Conch/Route/Workspace.pm
  Conch/t/integration/05_v1_schema.t
  Conch/t/model/ValidationState.t
Labels: api, enhancement

#228 feat: allow device services to be queried by name
  Conch/lib/Conch/Controller/DeviceServices.pm
  Conch/lib/Conch/Route/Device.pm
  Conch/t/integration/04_test_datacenter_loaded.t
  Conch/t/integration/05_v1_schema.t
Labels: api, enhancement

#231 fix: Fix few Validations, add tests
  Conch/lib/Conch/Validation/RamTotal.pm
  Conch/lib/Conch/Validation/SasHddNum.pm
  Conch/lib/Conch/Validation/SasSsdNum.pm
  Conch/lib/Conch/Validation/UsbHddNum.pm
  Conch/t/validations/ram_total_v1.t
  Conch/t/validations/sas_hdd_num_v1.t
  Conch/t/validations/sas_ssd_num_v1.t
  Conch/t/validations/usb_hdd_num_v1.t
Labels: bug

#229 fix: UI Login improvements
  Conch/ui/src/models/Auth.js
  Conch/ui/src/views/Login.js
Labels: bug

#233 feat: Integrate Validation State reporting into existing UI
  Conch/ui/src/models/Validation.js
  Conch/ui/src/models/ValidationPlan.js
  Conch/ui/src/models/ValidationState.js
  Conch/ui/src/views/Device.js
  Conch/ui/src/views/Problem.js
Labels: ui

#235 fix: orc workflows no longer have a product id but no one told that to the incoming json schema or the tests
  Conch/json-schema/input.yaml
  Conch/t/integration/orc/build.t
Labels: api, bug

#236 refactor: simplify Validation schema
  Conch/docs/validation/BaseValidation.md
  Conch/lib/Conch/Validation.pm
  Conch/lib/Conch/Validation/BiosFirmwareVersion.pm
  Conch/lib/Conch/Validation/CpuCount.pm
  Conch/lib/Conch/Validation/CpuTemperature.pm
  Conch/lib/Conch/Validation/DeviceProductName.pm
  Conch/lib/Conch/Validation/DimmCount.pm
  Conch/lib/Conch/Validation/RamTotal.pm
  Conch/lib/Conch/Validation/SwitchPeers.pm
Labels: refactor

#238 feat: Remove versions from orc workflows and lifecycles, making the name alone unique, and remove the ability to deactivate lifecycles and workflows
  Conch/json-schema/v1.yaml
  Conch/lib/Conch/Controller/Orc/Lifecycles.pm
  Conch/lib/Conch/Controller/Orc/Workflows.pm
  Conch/lib/Conch/Orc/Lifecycle.pm
  Conch/lib/Conch/Orc/Workflow.pm
  Conch/lib/Conch/Route/Orc.pm
  Conch/t/integration/orc/build.t
  sql/migrations/0027-orc-simplification.sql
Labels: api, enhancement

#237 doc: Add Guide for Validations
  Conch/docs/validation/Guide.md
Labels: docs
