Repository joyent/conch-api, pull requests merged in 2018-07, with the labels that each got.

#287 fix: Update switchpeers validation to support Arista deployments
  Conch/lib/Conch/Validation/SwitchPeers.pm
  Conch/t/validations/switch_peers_v1.t
Labels: bug, enhancement

#291 refactor: the unparsable logger is no longer used with the new validation system so remove the dead code
  Conch/lib/Conch.pm
Labels: refactor

#292 fix: update the DeviceProductName validation to handle the new naming scheme
  Conch/lib/Conch/Validation.pm
  Conch/lib/Conch/Validation/DeviceProductName.pm
  Conch/t/integration/resource/passing-device-report.json
  Conch/t/model/Validation.t
  Conch/t/model/ValidationState.t
  Conch/t/validations/device_product_name_v1.t
Labels: bug, enhancement

#293 better json handling
  .gitignore
  Conch/bin/conch
  Conch/cpanfile
  Conch/cpanfile.snapshot
Labels: enhancement

#294 Remove the ability to load validation plans via the app config
  Conch/conch.conf.dist
  Conch/lib/Conch.pm
  Conch/lib/Conch/Controller/DeviceReport.pm
  Conch/lib/Conch/ValidationSystem.pm
  Conch/lib/Test/Conch/Datacenter.pm
  Conch/t/integration/02_hardware_product_profiles_loaded.t
  Conch/t/integration/03_zpool_profiles_loaded.t
  Conch/t/integration/05_response_schema.t
Labels: enhancement, tests

#296 In audit logs, don't log JWT data and log only json in each line
  Conch/lib/Conch.pm
Labels: enhancement

#298 when handling an exception, use the exception that is always in the stash but not always in the args
  Conch/lib/Conch.pm
Labels: bug, enhancement

#299 Minor tweaks to DB Hardware Products
  Conch/json-schema/input.yaml
  Conch/lib/Conch/Controller/DB/HardwareProduct.pm
Labels: enhancement

#301 do not build the doc target automatically
  Conch/Makefile
Labels: build

#311 db refactoring and change password interface
  bin/conch_pw_hash
  cpanfile
  cpanfile.snapshot
  json-schema/input.yaml
  lib/Conch.pm
  lib/Conch/Command/create_user.pm
  lib/Conch/Controller/Login.pm
  lib/Conch/Controller/User.pm
  lib/Conch/Controller/WorkspaceUser.pm
  lib/Conch/DB/Result/UserAccount.pm
  lib/Conch/DB/Result/UserSetting.pm
  lib/Conch/DB/ResultSet/UserAccount.pm
  lib/Conch/DB/ResultSet/UserSessionToken.pm
  lib/Conch/DB/ResultSet/UserSetting.pm
  lib/Conch/Model/SessionToken.pm
  lib/Conch/Model/User.pm
  lib/Conch/Route.pm
  lib/Conch/Route/DB/HardwareProduct.pm
  lib/Conch/Route/Datacenter.pm
  lib/Conch/Route/Device.pm
  lib/Conch/Route/User.pm
  lib/Test/ConchTmpDB.pm
  t/integration/00_only_1_user_loaded.t
  t/integration/04_test_datacenter_loaded.t
  t/model/Device.t
  t/model/Relay.t
  t/model/SessionToken.t
  t/model/User.t
  t/model/Workspace.t
  t/model/WorkspaceUser.t
Labels: enhancement, refactor

#314 remove the unused JsonValidator->status_with_validation
  lib/Conch/Plugin/JsonValidator.pm
Labels: refactor

#315 fix an issue in the status helper where we were operating on main app and not the controller
  lib/Conch.pm
Labels: bug

#316 create a wrapper for Test::Mojo that sets up the conch app
  lib/Test/Conch.pm
  lib/Test/Conch/Datacenter.pm
  lib/Test/ConchTmpDB.pm
  lib/Test/MojoSchema.pm
  t/integration/00_only_1_user_loaded.t
  t/integration/01_hardware_products_loaded.t
  t/integration/02_hardware_product_profiles_loaded.t
  t/integration/03_zpool_profiles_loaded.t
  t/integration/04_test_datacenter_loaded.t
  t/integration/05_response_schema.t
  t/integration/06_secured_endpoints.t
  t/integration/crud/datacenter.t
  t/integration/crud/hardware_product.t
  t/integration/crud/rack_layouts.t
  t/integration/crud/rack_roles.t
  t/integration/crud/racks.t
Labels: enhancement, tests
