Repository joyent/conch-api, pull requests merged in 2018-06, with the labels that each got.

#266 CRUD for datacenter and datacenter_room
  Conch/json-schema/input.yaml
  Conch/lib/Conch/Controller/Datacenter.pm
  Conch/lib/Conch/Controller/DatacenterRoom.pm
  Conch/lib/Conch/Model/Datacenter.pm
  Conch/lib/Conch/Model/DatacenterRoom.pm
  Conch/lib/Conch/Models.pm
  Conch/lib/Conch/Route.pm
  Conch/lib/Conch/Route/Datacenter.pm
  Conch/t/integration/01_hardware_products_loaded.t
  Conch/t/integration/04_test_datacenter_loaded.t
  Conch/t/model/Datacenter.t
  Conch/t/model/DatacenterRoom.t
  sql/migrations/0033-datacenter-crud-cleanup.sql
Labels: enhancement

#268 fix(api): serialize validation result order
  Conch/json-schema/response.yaml
  Conch/lib/Conch/Model/ValidationResult.pm
Labels: bug

#269 feat: CRUD for datacenter_rack_layout
  Conch/json-schema/input.yaml
  Conch/json-schema/response.yaml
  Conch/lib/Conch/Controller/DatacenterRack.pm
  Conch/lib/Conch/Controller/DatacenterRackLayout.pm
  Conch/lib/Conch/Model/DatacenterRackLayout.pm
  Conch/lib/Conch/Models.pm
  Conch/lib/Conch/Route/Datacenter.pm
  Conch/t/integration/01_hardware_products_loaded.t
  Conch/t/integration/04_test_datacenter_loaded.t
  Conch/t/model/DatacenterRackLayout.t
Labels: enhancement

#270 fix: Plugin::JsonValidator now throws exceptions when asked to validate a nonexistent schema
  Conch/json-schema/input.yaml
  Conch/lib/Conch/Plugin/JsonValidator.pm
Labels: bug

#271 fix: in the json-schema for DatacenterUpdate, allow users to update the location property
  Conch/json-schema/input.yaml
Labels: bug

#272 refactor: in the device report handling, set the jsonb field to the raw body received from the client, rather than bouncing through the json lib twice
  Conch/lib/Conch/Controller/DeviceReport.pm
  Conch/lib/Conch/Legacy/Control/DeviceReport.pm
Labels: refactor

#275 feat: move auth handlers into a plugin and add a new helper to allow admin access to global admins as well as workspace admins
  Conch/lib/Conch.pm
  Conch/lib/Conch/Plugin/AuthHelpers.pm
Labels: enhancement

#276 feat: increase the length of generated passwords and add non-alpha characters to them
  Conch/lib/Conch.pm
  Conch/lib/Conch/Controller/Login.pm
  Conch/lib/Conch/Controller/WorkspaceUser.pm
Labels: enhancement

#277 feat: do not send emails to existing users when they are added to a new workspace
  Conch/lib/Conch/Controller/WorkspaceUser.pm
  Conch/lib/Conch/Mail.pm
  Conch/lib/Conch/Plugin/Mail.pm
Labels: enhancement

#278 feat: Adjust permissions in workspace operations to limit most writes to admins only, and open "admin" to global admins as well
  Conch/lib/Conch/Controller/Workspace.pm
  Conch/lib/Conch/Controller/WorkspaceRack.pm
  Conch/lib/Conch/Controller/WorkspaceRoom.pm
  Conch/lib/Conch/Controller/WorkspaceUser.pm
Labels: enhancement

#285 tests: move CRUD tests into their own files
  Conch/t/integration/04_test_datacenter_loaded.t
  Conch/t/integration/crud/datacenter.t
  Conch/t/integration/crud/rack_layouts.t
  Conch/t/integration/crud/rack_roles.t
  Conch/t/integration/crud/racks.t
Labels: tests
