Repository joyent/conch-api, pull requests merged in 2018-05, with the labels that each got.

#243 feat: add query parameter filtering for validation states
  Conch/lib/Conch/Controller/DeviceValidation.pm
  Conch/lib/Conch/Controller/WorkspaceValidation.pm
  Conch/lib/Conch/Model/ValidationState.pm
  Conch/t/integration/04_test_datacenter_loaded.t
Labels: api, enhancement

#245 Replace Data::Validate::UUID with Conch::UUID
  Conch/cpanfile
  Conch/cpanfile.snapshot
  Conch/lib/Conch/Controller/Device.pm
  Conch/lib/Conch/Controller/DeviceLocation.pm
  Conch/lib/Conch/Controller/DeviceReport.pm
  Conch/lib/Conch/Controller/HardwareProduct.pm
  Conch/lib/Conch/Controller/Relay.pm
  Conch/lib/Conch/Controller/ValidationPlan.pm
  Conch/lib/Conch/Controller/Workspace.pm
  Conch/lib/Conch/Controller/WorkspaceRack.pm
  Conch/lib/Conch/Model/Device.pm
  Conch/lib/Conch/Model/User.pm
  Conch/lib/Conch/Plugin/JsonValidator.pm
  Conch/lib/Conch/UUID.pm
  Conch/t/conch_uuid.t
  Conch/t/integration/05_v1_schema.t
  Conch/t/integration/orc/build.t
  Conch/t/integration/orc/workflows.t
Labels: bug, refactor

#248 fix: require that Content-Type with application/json is specified
  Conch/lib/Conch.pm
  Conch/t/integration/00_only_1_user_loaded.t
  Conch/t/integration/01_hardware_products_loaded.t
  Conch/t/integration/02_hardware_product_profiles_loaded.t
  Conch/t/integration/03_zpool_profiles_loaded.t
  Conch/t/integration/04_test_datacenter_loaded.t
  Conch/t/integration/05_v1_schema.t
Labels: bug, security

#249 Refactor: workspace devices stored procedure, validation states queries
  Conch/lib/Conch/Controller/DeviceValidation.pm
  Conch/lib/Conch/Controller/WorkspaceValidation.pm
  Conch/lib/Conch/Model/ValidationResult.pm
  Conch/lib/Conch/Model/ValidationState.pm
  Conch/lib/Conch/Model/WorkspaceDevice.pm
  Conch/t/model/ValidationState.t
  sql/migrations/0031-workspace-devices-fn.sql
Labels: refactor

#251 BREAKING: remove orchestration
  Conch/conch.conf.dist
  Conch/lib/Conch/Controller/DeviceSettings.pm
  Conch/lib/Conch/Controller/Orc/Lifecycles.pm
  Conch/lib/Conch/Controller/Orc/WorkflowSteps.pm
  Conch/lib/Conch/Controller/Orc/Workflows.pm
  Conch/lib/Conch/Orc.pm
  Conch/lib/Conch/Orc/Lifecycle.pm
  Conch/lib/Conch/Orc/Workflow.pm
  Conch/lib/Conch/Orc/Workflow/Status.pm
  Conch/lib/Conch/Orc/Workflow/Step.pm
  Conch/lib/Conch/Orc/Workflow/Step/Status.pm
  Conch/lib/Conch/Role/But.pm
  Conch/lib/Conch/Route.pm
  Conch/lib/Conch/Route/Orc.pm
  Conch/t/integration/orc/build.t
  Conch/t/integration/orc/workflows.t
  Conch/t/orc/00-load.t
  Conch/t/orc/01-workflow.t
  Conch/t/orc/02-workflow_status.t
  Conch/t/orc/03-workflow_step.t
  Conch/t/orc/04-workflow_step_status.t
  Conch/t/orc/05-workflow_steps.t
  Conch/t/orc/06-lifecycle.t
  sql/migrations/0032-remove-orc.sql
Labels: api, breaking

#246 feat: Add JWT as a method of authentication
  Conch/conch.conf.dist
  Conch/cpanfile
  Conch/cpanfile.snapshot
  Conch/json-schema/v1.yaml
  Conch/lib/Conch/Controller/Login.pm
  Conch/lib/Conch/Controller/User.pm
  Conch/lib/Conch/Model/SessionToken.pm
  Conch/lib/Conch/Route.pm
  Conch/lib/Conch/Route/User.pm
  Conch/t/integration/00_only_1_user_loaded.t
  Conch/t/integration/05_v1_schema.t
  Conch/t/model/SessionToken.t
  sql/migrations/0030-user-session-token.sql
Labels: api, enhancement

#254 fix: in session_login, stash the user id so that is_global_admin will work, even if we are using JWT auth
  Conch/lib/Conch/Controller/Login.pm
Labels: bug

#252 feat: Add development CORS headers
  Conch/lib/Conch.pm
  Conch/lib/Conch/Route.pm
Labels: api

#253 refactor: Remove UI
  .gitignore
  Conch/Makefile
  Conch/lib/Conch/Route.pm
  Conch/public/css/d3.relationshipgraph.min.css
  Conch/public/css/error.css
  Conch/public/css/grids-responsive-min.css
  Conch/public/css/pure-min.css
  Conch/public/css/style.css
  Conch/public/favicon.ico
  Conch/public/images/logo-white.svg
  Conch/public/js/.keep
  Conch/templates/index.html.ep
  Conch/ui/.babelrc
  Conch/ui/.eslintrc.js
  Conch/ui/.gitignore
  Conch/ui/.jshintrc
  Conch/ui/.prettierrc
  Conch/ui/DESIGN.md
  Conch/ui/README.md
  Conch/ui/css/app.css
  Conch/ui/package.json
  Conch/ui/src/index.js
  Conch/ui/src/languages/en.js
  Conch/ui/src/languages/ko.js
  Conch/ui/src/models/Auth.js
  Conch/ui/src/models/Device.js
  Conch/ui/src/models/Feedback.js
  Conch/ui/src/models/Problem.js
  Conch/ui/src/models/Rack.js
  Conch/ui/src/models/Relay.js
  Conch/ui/src/models/Validation.js
  Conch/ui/src/models/ValidationPlan.js
  Conch/ui/src/models/ValidationState.js
  Conch/ui/src/models/Workspace.js
  Conch/ui/src/views/Device.js
  Conch/ui/src/views/Feedback.js
  Conch/ui/src/views/Layout.js
  Conch/ui/src/views/Login.js
  Conch/ui/src/views/Problem.js
  Conch/ui/src/views/Rack.js
  Conch/ui/src/views/Relay/Detail.js
  Conch/ui/src/views/Relay/List.js
  Conch/ui/src/views/Status.js
  Conch/ui/src/views/Status/RackProgress.js
  Conch/ui/src/views/component/DeviceStatus.js
  Conch/ui/src/views/component/Icons.js
  Conch/ui/src/views/component/Table.js
  Conch/ui/webpack.config.js
  Conch/ui/yarn.lock
Labels: refactor

#257 build: remove the travis deploy
  .travis.yml
Labels: build

#261 refactor: Remove old validation system
  Conch/conch.conf.dist
  Conch/json-schema/v1.yaml
  Conch/lib/Conch/Controller/DeviceReport.pm
  Conch/lib/Conch/Legacy/Control/Device/Configuration.pm
  Conch/lib/Conch/Legacy/Control/Device/Environment.pm
  Conch/lib/Conch/Legacy/Control/Device/Inventory.pm
  Conch/lib/Conch/Legacy/Control/Device/Network.pm
  Conch/lib/Conch/Legacy/Control/Device/Validation.pm
  Conch/lib/Conch/Legacy/Control/DeviceReport.pm
  Conch/t/integration/02_hardware_product_profiles_loaded.t
  Conch/t/integration/03_zpool_profiles_loaded.t
  Conch/t/integration/04_test_datacenter_loaded.t
  Conch/t/integration/05_v1_schema.t
Labels: enhancement, refactor

#263 Remove v1 references
  Conch/json-schema/response.yaml
  Conch/lib/Conch/Class/DatacenterRack.pm
  Conch/lib/Conch/Class/DatacenterRoom.pm
  Conch/lib/Conch/Class/DeviceDetailed.pm
  Conch/lib/Conch/Class/DeviceLocation.pm
  Conch/lib/Conch/Class/HardwareProduct.pm
  Conch/lib/Conch/Class/HardwareProductProfile.pm
  Conch/lib/Conch/Class/Relay.pm
  Conch/lib/Conch/Class/Role/ToJson.pm
  Conch/lib/Conch/Class/Workspace.pm
  Conch/lib/Conch/Class/WorkspaceRelay.pm
  Conch/lib/Conch/Class/WorkspaceRole.pm
  Conch/lib/Conch/Class/WorkspaceUser.pm
  Conch/lib/Conch/Class/ZpoolProfile.pm
  Conch/lib/Conch/Controller/Device.pm
  Conch/lib/Conch/Controller/DeviceLocation.pm
  Conch/lib/Conch/Controller/HardwareProduct.pm
  Conch/lib/Conch/Controller/Relay.pm
  Conch/lib/Conch/Controller/Workspace.pm
  Conch/lib/Conch/Controller/WorkspaceDevice.pm
  Conch/lib/Conch/Controller/WorkspaceRelay.pm
  Conch/lib/Conch/Controller/WorkspaceRoom.pm
  Conch/lib/Conch/Controller/WorkspaceUser.pm
  Conch/lib/Conch/Model/Device.pm
  Conch/lib/Conch/Model/Relay.pm
  Conch/lib/Conch/Plugin/JsonValidator.pm
  Conch/t/class/DatacenterRack.t
  Conch/t/class/Workspace.t
  Conch/t/integration/00_only_1_user_loaded.t
  Conch/t/integration/04_test_datacenter_loaded.t
  Conch/t/integration/05_response_schema.t
  Conch/t/model/Relay.t
Labels: refactor

#264 Vision doc
  Conch/docs/vison.md
Labels: docs

#265 feat: add a no_devices flag to getRelays to allow the user to opt out of retrieving all the devices for a relay
  Conch/lib/Conch/Controller/WorkspaceRelay.pm
  Conch/lib/Conch/Model/WorkspaceRelay.pm
  Conch/t/integration/04_test_datacenter_loaded.t
Labels: enhancement
