Repository joyent/conch-api, pull requests merged in 2018-12, with the labels that each got.

#568 moar conch model removal
  json-schema/input.yaml
  lib/Conch/Class/DatacenterRack.pm
  lib/Conch/Class/DatacenterRoom.pm
  lib/Conch/Class/DeviceLocation.pm
  lib/Conch/Class/Relay.pm
  lib/Conch/Controller/Device.pm
  lib/Conch/Controller/DeviceLocation.pm
  lib/Conch/Controller/DeviceReport.pm
  lib/Conch/Controller/DeviceValidation.pm
  lib/Conch/Controller/Relay.pm
  lib/Conch/Controller/WorkspaceRack.pm
  lib/Conch/Controller/WorkspaceRoom.pm
  lib/Conch/DB/Result/Relay.pm
  lib/Conch/DB/ResultSet/DeviceLocation.pm
  lib/Conch/Model/Device.pm
  lib/Conch/Model/DeviceLocation.pm
  lib/Conch/Model/Relay.pm
  lib/Conch/Model/ValidationPlan.pm
  lib/Conch/Model/WorkspaceRack.pm
  lib/Conch/Model/WorkspaceRoom.pm
  lib/Conch/Models.pm
  t/class/DatacenterRack.t
  t/integration/04_test_datacenter_loaded.t
  t/integration/crud/devices.t
  t/model/Device.t
  t/model/DeviceLocation.t
  t/model/Relay.t
  t/model/Validation.t
  t/model/ValidationPlan.t
  t/model/ValidationResult.t
  t/model/ValidationState.t
  t/model/WorkspaceRack.t
  t/model/WorkspaceRoom.t
Labels: api, refactor

#569 convert and remove Conch::Model::WorkspaceRelay
  json-schema/response.yaml
  lib/Conch/Class/Role/ToJson.pm
  lib/Conch/Class/WorkspaceRelay.pm
  lib/Conch/Controller/WorkspaceRelay.pm
  lib/Conch/Model/Device.pm
  lib/Conch/Model/WorkspaceRelay.pm
  lib/Conch/Models.pm
  lib/Conch/Route/Workspace.pm
  lib/Test/Conch.pm
  lib/Test/Conch/Fixtures.pm
  t/integration/04_test_datacenter_loaded.t
  t/integration/crud/relay.t
  t/model/WorkspaceRelay.t
Labels: api, enhancement, needs-shell, refactor

#571 saner validation interfaces
  cpanfile
  lib/Conch/Controller/DeviceReport.pm
  lib/Conch/Controller/DeviceSettings.pm
  lib/Conch/Controller/DeviceValidation.pm
  lib/Conch/DB/Result/Device.pm
  lib/Conch/DB/Result/ValidationState.pm
  lib/Conch/Model/Validation.pm
  lib/Conch/Model/ValidationPlan.pm
  lib/Conch/Model/ValidationResult.pm
  lib/Conch/Model/ValidationState.pm
  lib/Conch/Models.pm
  lib/Conch/Validation.pm
  lib/Conch/ValidationSystem.pm
  lib/Test/Conch.pm
  lib/Test/Conch/Fixtures.pm
  lib/Test/Conch/Validation.pm
  t/lib/Conch/Validation/MissingCategory.pm
  t/lib/Conch/Validation/MultipleResults.pm
  t/model/Validation.t
  t/model/ValidationPlan.t
  t/model/ValidationResult.t
  t/model/ValidationState.t
  t/validation-system/check_validations.t
  t/validation-system/run_validations.t
Labels: refactor

#572 disable validation endpoints that alter data
  lib/Conch/Controller/ValidationPlan.pm
  lib/Conch/Route/Validation.pm
  t/integration/04_test_datacenter_loaded.t
Labels: api

#575 Better utilize server resources by switching the production Dockerfile to use hypnotoad
  Dockerfile
  docker/compose.yml.dist
Labels: api, build, enhancement

#576 do not let Conch::Pg tear down our db connection
  lib/Conch/Pg.pm
Labels: database

#578 do not include deactivated rows in hardware_product unique constraints
  lib/Conch/DB/Result/HardwareProduct.pm
  sql/migrations/0067-hardware_product-unique.sql
  sql/schema.sql
Labels: bug, database

#582 moar hardware product fixes
  json-schema/input.yaml
  lib/Conch/Controller/HardwareProduct.pm
  t/integration/crud/hardware_product.t
Labels: api, bug, enhancement

#584 better datacenter endpoints
  json-schema/input.yaml
  json-schema/response.yaml
  lib/Conch/Command/check_layouts.pm
  lib/Conch/Controller/Datacenter.pm
  lib/Conch/Controller/DatacenterRack.pm
  lib/Conch/Controller/DatacenterRackLayout.pm
  lib/Conch/Controller/DatacenterRackRole.pm
  lib/Conch/Controller/DatacenterRoom.pm
  lib/Conch/DB/Result/DatacenterRackLayout.pm
  lib/Conch/DB/ResultSet/DatacenterRack.pm
  lib/Conch/Route/Datacenter.pm
  lib/Conch/Validation/DeviceProductName.pm
  lib/Test/Conch/Fixtures.pm
  t/integration/crud/datacenter.t
  t/integration/crud/rack_layouts.t
  t/integration/crud/rack_roles.t
  t/integration/crud/racks.t
  t/integration/crud/relay.t
  t/integration/crud/rooms.t
Labels: api, bug, enhancement, needs-shell

#585 fix GET /device?key=value endpoint to search for and return multiple devices
  lib/Conch/Controller/Device.pm
  lib/Conch/Route/Device.pm
  t/integration/04_test_datacenter_loaded.t
Labels: api, bug, enhancement, needs-shell

#589 mutating device settings now only requires "rw" perms for all settings
  lib/Conch/Controller/DeviceSettings.pm
  t/integration/04_test_datacenter_loaded.t
Labels: api

#591 final 2.22 fixes
  README.md
  docs/validation/BaseValidation.md
  docs/validation/Guide.md
  docs/vison.md
  json-schema/input.yaml
  lib/Conch.pm
  lib/Conch/Plugin/Database.pm
  lib/Conch/Plugin/GitVersion.pm
  lib/Test/Conch.pm
  sql/migrations/0068-device_location.sql
  sql/schema.sql
Labels: database, docs
