Repository joyent/conch-api, pull requests merged in 2018-10, with the labels that each got.

#480 fix "workspaces" command
  lib/Conch/Command/workspaces.pm
Labels: bug

#482 make device_setting.value nullable
  lib/Conch/DB/Result/DeviceSetting.pm
  lib/Conch/DB/Result/UserSetting.pm
  lib/Conch/Model/Validation.pm
  lib/Conch/Model/ValidationPlan.pm
  sql/migrations/0057-user-device_settings.sql
  sql/schema.sql
Labels: database

#483 fix: do not create duplicate validation_state records
  lib/Conch/Model/ValidationState.pm
  t/model/ValidationPlan.t
Labels: bug

#485 add some missing indexes on foreign keys
  lib/Conch/DB/Result/HardwareProduct.pm
  sql/migrations/0058-validation_state-to-device_report.sql
  sql/schema.sql
Labels: database

#486 some test cleanup, and adding missing json schemas and documentation thereof
  json-schema/input.yaml
  json-schema/response.yaml
  lib/Conch/Controller/DB/HardwareProduct.pm
  lib/Conch/Controller/DeviceLocation.pm
  lib/Conch/Controller/DeviceReport.pm
  lib/Conch/Controller/DeviceValidation.pm
  lib/Conch/Controller/HardwareProduct.pm
  lib/Conch/Controller/HardwareVendor.pm
  lib/Conch/Controller/Relay.pm
  lib/Conch/Controller/Validation.pm
  lib/Conch/Controller/ValidationPlan.pm
  lib/Conch/Controller/WorkspaceRack.pm
  lib/Conch/Controller/WorkspaceRelay.pm
  lib/Conch/Controller/WorkspaceRoom.pm
  t/integration/00_only_1_user_loaded.t
  t/integration/01_hardware_products_loaded.t
  t/integration/02_hardware_product_profiles_loaded.t
  t/integration/03_zpool_profiles_loaded.t
  t/integration/04_test_datacenter_loaded.t
  t/integration/05_response_schema.t
  t/integration/crud/hardware_product.t
Labels: tests

#489 fix creation, re-use of validation_state records
  lib/Conch/Model/ValidationPlan.pm
  lib/Conch/Model/ValidationState.pm
  t/model/ValidationPlan.t
  t/model/ValidationState.t
Labels: bug

#490 save device_report_id on validation_state; never re-use old records
  json-schema/response.yaml
  lib/Conch/Command/update_validation_states.pm
  lib/Conch/Controller/DeviceReport.pm
  lib/Conch/DB/Result/DeviceReport.pm
  lib/Conch/DB/Result/ValidationState.pm
  lib/Conch/Model/ValidationPlan.pm
  lib/Conch/Model/ValidationState.pm
  sql/migrations/0060-validation_state-device_report_id.sql
  sql/schema.sql
  t/integration/04_test_datacenter_loaded.t
  t/model/ValidationPlan.t
  t/model/ValidationResult.t
  t/model/ValidationState.t
Labels: database

#492 do not store device report if it matches a previous report
  lib/Conch/Controller/Device.pm
  lib/Conch/Controller/DeviceReport.pm
  lib/Conch/DB/Result/Device.pm
  lib/Conch/DB/Result/DeviceReport.pm
  lib/Conch/DB/ResultSet/Device.pm
  sql/migrations/0061-device_report-received_count.sql
  sql/schema.sql
  t/integration/04_test_datacenter_loaded.t
Labels: enhancement

#493 populate validation_state.device_report_id and make it not nullable
  json-schema/response.yaml
  lib/Conch/DB/Result/ValidationState.pm
  sql/migrations/0062-device_report_id-not-nullable.sql
  sql/schema.sql
Labels: database

#497 Some cleanup of database stuff
  cpanfile
  lib/Conch.pm
  lib/Conch/Controller/DB/HardwareProduct.pm
  lib/Conch/Controller/Device.pm
  lib/Conch/Controller/DeviceReport.pm
  lib/Conch/Controller/DeviceSettings.pm
  lib/Conch/Controller/User.pm
  lib/Conch/Controller/Workspace.pm
  lib/Conch/Controller/WorkspaceProblem.pm
  lib/Conch/DB.pm
  lib/Conch/DB/Result/UserAccount.pm
  lib/Conch/DB/ResultSet/DatacenterRack.pm
  lib/Conch/DB/ResultSet/Device.pm
  lib/Conch/DB/ResultSet/UserAccount.pm
  lib/Conch/DB/ResultSet/Workspace.pm
  lib/Test/ConchTmpDB.pm
  t/integration/00_only_1_user_loaded.t
  t/model/Relay.t
  t/model/WorkspaceRack.t
  t/model/WorkspaceRoom.t
  t/test-conch.t
Labels: database

#499 20181012 misc cleanup
  Makefile
  cpanfile
  cpanfile.snapshot
  json-schema/input.yaml
  json-schema/response.yaml
  lib/Conch/Command/workspaces.pm
  lib/Conch/Controller/Datacenter.pm
  lib/Conch/Controller/DatacenterRack.pm
  lib/Conch/Controller/DatacenterRackLayout.pm
  lib/Conch/Controller/DatacenterRackRole.pm
  lib/Conch/Controller/DatacenterRoom.pm
  lib/Conch/Controller/DeviceReport.pm
  lib/Conch/Controller/DeviceValidation.pm
  lib/Conch/Controller/HardwareVendor.pm
  lib/Conch/Controller/Login.pm
  lib/Conch/Controller/ValidationPlan.pm
  lib/Conch/Controller/WorkspaceProblem.pm
  lib/Conch/Controller/WorkspaceRack.pm
  lib/Conch/Model/ValidationState.pm
  lib/Conch/Route/Workspace.pm
  t/integration/00_only_1_user_loaded.t
  t/integration/04_test_datacenter_loaded.t
Labels: api, refactor, tests

#500 do not require user_account.name to be unique
  json-schema/input.yaml
  lib/Conch/Controller/Login.pm
  lib/Conch/Controller/User.pm
  lib/Conch/Controller/WorkspaceUser.pm
  lib/Conch/DB/ResultSet/UserAccount.pm
  sql/migrations/0063-user_account-name-not-unique.sql
  sql/schema.sql
  t/integration/00_only_1_user_loaded.t
Labels: database, enhancement

#502 POST /user/<id or email> for updating user attributes
  json-schema/input.yaml
  lib/Conch/Controller/Login.pm
  lib/Conch/Controller/User.pm
  lib/Conch/Controller/WorkspaceUser.pm
  lib/Conch/DB/ResultSet/UserAccount.pm
  lib/Conch/Route/User.pm
  lib/Conch/Route/Workspace.pm
  t/integration/00_only_1_user_loaded.t
Labels: api, enhancement

#509 20181017 misc cleanup
  lib/Conch.pm
  lib/Conch/Command/create_user.pm
  lib/Conch/Controller/DB/HardwareProduct.pm
  lib/Conch/Controller/DatacenterRack.pm
  lib/Conch/Controller/DatacenterRackLayout.pm
  lib/Conch/Controller/DatacenterRackRole.pm
  lib/Conch/Controller/Device.pm
  lib/Conch/Controller/DeviceInterface.pm
  lib/Conch/Controller/DeviceLocation.pm
  lib/Conch/Controller/DeviceSettings.pm
  lib/Conch/Controller/Login.pm
  lib/Conch/Controller/Relay.pm
  lib/Conch/Controller/User.pm
  lib/Conch/Controller/Workspace.pm
  lib/Conch/Controller/WorkspaceUser.pm
  lib/Conch/DB/Result/Device.pm
  lib/Conch/DB/ResultSet.pm
  lib/Conch/DB/ResultSet/DeviceSetting.pm
  lib/Conch/DB/ResultSet/UserWorkspaceRole.pm
  lib/Conch/DB/ResultsExist.pm
  lib/Conch/Plugin/Mail.pm
  lib/Conch/Route.pm
  lib/Conch/Route/DB/HardwareProduct.pm
  lib/Conch/Route/Datacenter.pm
  lib/Conch/Route/Device.pm
  lib/Conch/Route/HardwareProduct.pm
  lib/Conch/Route/Relay.pm
  lib/Conch/Route/User.pm
  lib/Conch/Route/Validation.pm
  lib/Conch/Route/Workspace.pm
  lib/Conch/ValidationSystem.pm
  lib/Test/Conch/Datacenter.pm
  lib/Test/Conch/Validation.pm
  sql/migrations/0064-more-missing-indexes.sql
  sql/schema.sql
  t/integration/01_hardware_products_loaded.t
  t/integration/02_hardware_product_profiles_loaded.t
  t/integration/03_zpool_profiles_loaded.t
  t/integration/06_secured_endpoints.t
  t/integration/crud/datacenter.t
  t/integration/crud/hardware_product.t
  t/integration/crud/rack_layouts.t
  t/integration/crud/rack_roles.t
  t/integration/crud/racks.t
Labels: database

#515 do not delete nics when processing subsequent reports
  lib/Conch/Controller/DeviceReport.pm
Labels: bug

#514 fix problems with rollbar payloads
  lib/Conch/Plugin/Logging.pm
  lib/Conch/Plugin/Rollbar.pm
Labels: bug

#521 properly share db connections
  cpanfile
  cpanfile.snapshot
  lib/Conch.pm
  lib/Conch/Plugin/Logging.pm
  lib/Test/Conch.pm
  t/database.t
  t/integration/00_only_1_user_loaded.t
Labels: bug, database, high priority

#519 collapse /db/hardware_product endpoints into /hardware_product
  cpanfile
  cpanfile.snapshot
  json-schema/input.yaml
  json-schema/response.yaml
  lib/Conch/Class/HardwareProduct.pm
  lib/Conch/Class/HardwareProductProfile.pm
  lib/Conch/Class/ZpoolProfile.pm
  lib/Conch/Controller/DB/HardwareProduct.pm
  lib/Conch/Controller/DatacenterRackLayout.pm
  lib/Conch/Controller/HardwareProduct.pm
  lib/Conch/DB/Result/HardwareProduct.pm
  lib/Conch/DB/Result/HardwareProductProfile.pm
  lib/Conch/DB/Result/ZpoolProfile.pm
  lib/Conch/Model/HardwareProduct.pm
  lib/Conch/Role/MojoLog.pm
  lib/Conch/Route.pm
  lib/Conch/Route/DB/HardwareProduct.pm
  lib/Conch/Route/HardwareProduct.pm
  schema-loader.yaml
  t/00-report-prereqs.t
  t/integration/01_hardware_products_loaded.t
  t/integration/02_hardware_product_profiles_loaded.t
  t/integration/03_zpool_profiles_loaded.t
  t/integration/crud/hardware_product.t
  t/model/HardwareProduct.t
Labels: api, breaking, needs-shell, needs-ui

#522 Provide infrastructure to build and test with Docker, including scripts for buildbot
  .dockerignore
  Dockerfile
  Dockerfile.dev
  Makefile
  docker/buildbot-prerelease.bash
  docker/buildbot-release.bash
  docker/builder.sh
  docker/dev_test.bash
  docker/remove_old_images.bash
  etc/.keep
Labels: build, tests
