Repository joyent/conch-api, pull requests merged in 2018-09, with the labels that each got.

#408 More fixes to WorkspaceRack output
  json-schema/response.yaml
  lib/Conch/Model/DeviceLocation.pm
  lib/Conch/Model/WorkspaceRack.pm
  t/conch_time.t
  t/database.t
  t/integration/01_hardware_products_loaded.t
  t/integration/02_hardware_product_profiles_loaded.t
  t/integration/03_zpool_profiles_loaded.t
  t/integration/04_test_datacenter_loaded.t
  t/integration/05_response_schema.t
  t/integration/06_secured_endpoints.t
  t/integration/crud/datacenter.t
  t/integration/crud/devices.t
  t/integration/crud/hardware_product.t
  t/integration/crud/rack_layouts.t
  t/integration/crud/rack_roles.t
  t/integration/crud/racks.t
  t/pod-coverage.t
  t/test-conch.t
Labels: bug

#410 add support for device hostnames
  json-schema/input.yaml
  json-schema/response.yaml
  lib/Conch/Controller/Device.pm
  lib/Conch/Controller/DeviceReport.pm
  lib/Conch/DB/Result/Device.pm
  lib/Conch/Model/Device.pm
  sql/migrations/0046-device-hostname.sql
  sql/schema.sql
  t/integration/04_test_datacenter_loaded.t
  t/integration/resource/passing-device-report.json
Labels: api

#415 fix reference to column name
  lib/Conch/Model/DeviceLocation.pm
Labels: bug

#416 this field is different in the input payload vs. the schema
  lib/Conch/Controller/DatacenterRackLayout.pm
Labels: bug

#420 modify hardware_vendor.name constraint to allow for deletions
  lib/Conch/DB/Result/HardwareVendor.pm
  sql/migrations/0048-hardware_vendor-name-unique.sql
  sql/schema.sql
Labels: bug, database

#421 in Controller::DatacenterRack#update, if the user provides a "role" parameter, map it to the new db field name
  lib/Conch/Controller/DatacenterRack.pm
Labels: bug

#417 rename columns for rack unit size, position; add FK; adjust formatting of WorkspaceRack response
  json-schema/input.yaml
  json-schema/response.yaml
  lib/Conch/Controller/DatacenterRackLayout.pm
  lib/Conch/Controller/DeviceLocation.pm
  lib/Conch/Controller/WorkspaceProblem.pm
  lib/Conch/Controller/WorkspaceRack.pm
  lib/Conch/DB/Result/DatacenterRackLayout.pm
  lib/Conch/DB/Result/DeviceLocation.pm
  lib/Conch/Model/DeviceLocation.pm
  lib/Conch/Model/WorkspaceRack.pm
  lib/Conch/Validation.pm
  lib/Conch/Validation/SwitchPeers.pm
  sql/migrations/0049-rack-unit-size-position.sql
  sql/schema.sql
  sql/test/03-test-datacenter.sql
  t/integration/04_test_datacenter_loaded.t
Labels: api, database, needs-shell, needs-ui

#424 generate CSV data for /workspace/:id/rack/:id
  cpanfile
  cpanfile.snapshot
  lib/Conch.pm
  lib/Conch/Controller/WorkspaceRack.pm
  lib/Conch/DB/ResultSet.pm
  t/integration/04_test_datacenter_loaded.t
Labels: enhancement, needs-ui

#425 remove endpoint: GET /workspace/:workspace_id/validation_state
  lib/Conch/Controller/WorkspaceValidation.pm
  lib/Conch/Model/ValidationState.pm
  lib/Conch/Route/Workspace.pm
  t/integration/04_test_datacenter_loaded.t
  t/integration/05_response_schema.t
Labels: api, breaking

#426 burn device_role, device_service and related join tables and FKs
  json-schema/response.yaml
  lib/Conch/Controller/Device.pm
  lib/Conch/Controller/DeviceRoles.pm
  lib/Conch/Controller/DeviceServices.pm
  lib/Conch/DB/Result/Device.pm
  lib/Conch/DB/Result/DeviceRole.pm
  lib/Conch/DB/Result/DeviceRoleService.pm
  lib/Conch/DB/Result/DeviceService.pm
  lib/Conch/DB/Result/HardwareProduct.pm
  lib/Conch/Model/Device.pm
  lib/Conch/Route/Device.pm
  sql/migrations/0050-burn-device_role-and-service.sql
  sql/schema.sql
  t/integration/04_test_datacenter_loaded.t
  t/integration/05_response_schema.t
Labels: api, breaking, database

#428 Documentation updates
  README.md
  config.yml
  docs/conch-api/index.js
  docs/conch-api/openapi-spec.yaml
  docs/conch-api/package.json
  docs/conch-api/yarn.lock
  docs/development.md
  docs/notes/2017-10-31-development-discussion.md
  docs/notes/2017-11-02-validation-use-cases.md
  docs/notes/2017-11-27-dbic-complaints.md
  docs/notes/2017-11-9-creating-workspace-and-user-with-api.md
  log4perl.conf
Labels: docs

#429 new endpoint to list all users+workspaces: GET /user
  json-schema/input.yaml
  json-schema/response.yaml
  lib/Conch/Controller/User.pm
  lib/Conch/DB/Result/UserAccount.pm
  lib/Conch/Route/User.pm
  schema-loader.yaml
  t/integration/00_only_1_user_loaded.t
Labels: needs-shell

#430 Changelog Generator
  cpanfile
  cpanfile.snapshot
  misc/README.md
  misc/ghch
  misc/nginx-conch.conf
Labels: docs

#432 DBIC infrastructure improvements
  Makefile
  lib/Conch.pm
  lib/Conch/Controller/Device.pm
  lib/Conch/Controller/User.pm
  lib/Conch/Controller/Workspace.pm
  lib/Conch/Controller/WorkspaceProblem.pm
  lib/Conch/DB/Result/DatacenterRack.pm
  lib/Conch/DB/Result/DatacenterRackLayout.pm
  lib/Conch/DB/Result/DatacenterRoom.pm
  lib/Conch/DB/Result/Device.pm
  lib/Conch/DB/Result/UserAccount.pm
  lib/Conch/DB/Result/UserRelayConnection.pm
  lib/Conch/DB/Result/WorkspaceDatacenterRack.pm
  lib/Conch/DB/Result/WorkspaceDatacenterRoom.pm
  lib/Conch/DB/ResultSet/DatacenterRack.pm
  lib/Conch/DB/ResultSet/Device.pm
  lib/Conch/DB/ResultSet/UserAccount.pm
  lib/Conch/DB/ResultSet/UserSetting.pm
  lib/Conch/DB/ResultSet/Workspace.pm
  lib/Conch/Plugin/AuthHelpers.pm
  sql/migrations/0051-not-nullable-fks.sql
  sql/schema.sql
Labels: database

#435 add unique index on device_settings.device_id+name
  sql/migrations/0052-device_settings-index.sql
  sql/schema.sql
Labels: database, enhancement

#449 search for device by arbitrary setting
  lib/Conch/Controller/Device.pm
  lib/Conch/Route/Device.pm
  t/integration/04_test_datacenter_loaded.t
Labels: enhancement

#457 Separate workspace 'admin' privileges from system administrator privileges
  conch.conf.dist
  docs/validation/Guide.md
  json-schema/response.yaml
  lib/Conch/Controller/DB/HardwareProduct.pm
  lib/Conch/Controller/Datacenter.pm
  lib/Conch/Controller/DatacenterRack.pm
  lib/Conch/Controller/DatacenterRackLayout.pm
  lib/Conch/Controller/DatacenterRackRole.pm
  lib/Conch/Controller/DatacenterRoom.pm
  lib/Conch/Controller/HardwareVendor.pm
  lib/Conch/Controller/Login.pm
  lib/Conch/Controller/Relay.pm
  lib/Conch/Controller/User.pm
  lib/Conch/Controller/ValidationPlan.pm
  lib/Conch/Controller/Workspace.pm
  lib/Conch/Controller/WorkspaceRack.pm
  lib/Conch/Controller/WorkspaceRoom.pm
  lib/Conch/Controller/WorkspaceUser.pm
  lib/Conch/DB/Result/UserAccount.pm
  lib/Conch/Plugin/AuthHelpers.pm
  lib/Conch/Route.pm
  lib/Conch/Route/User.pm
  lib/Conch/Route/Workspace.pm
  lib/Test/ConchTmpDB.pm
  sql/migrations/0053-user-account-admin-flag.sql
  sql/schema.sql
  t/integration/00_only_1_user_loaded.t
Labels: database, needs-shell

#463 workspace permissions are now inherited
  json-schema/response.yaml
  lib/Conch/Command/clean_permissions.pm
  lib/Conch/Command/workspaces.pm
  lib/Conch/Controller/Device.pm
  lib/Conch/Controller/User.pm
  lib/Conch/Controller/Workspace.pm
  lib/Conch/Controller/WorkspaceRack.pm
  lib/Conch/Controller/WorkspaceRoom.pm
  lib/Conch/Controller/WorkspaceUser.pm
  lib/Conch/DB/Result/UserAccount.pm
  lib/Conch/DB/Result/UserWorkspaceRole.pm
  lib/Conch/DB/Result/Workspace.pm
  lib/Conch/DB/ResultSet/Device.pm
  lib/Conch/DB/ResultSet/Workspace.pm
  lib/Conch/Plugin/AuthHelpers.pm
  sql/migrations/0055-recursive-permission-cleanup.sql
  t/integration/00_only_1_user_loaded.t
  t/integration/04_test_datacenter_loaded.t
  t/integration/05_response_schema.t
Labels: database, enhancement, needs-shell, needs-ui

#464 DELETE /workspace/:id/user/#target_user to remove a user from a workspace
  lib/Conch/Controller/WorkspaceUser.pm
  lib/Conch/Route/Workspace.pm
  t/integration/00_only_1_user_loaded.t
Labels: enhancement, needs-shell

#466 fix json encoding of device report
  json-schema/response.yaml
  lib/Conch/Controller/Device.pm
  lib/Conch/Controller/WorkspaceProblem.pm
  lib/Conch/DB/Result/Device.pm
  lib/Conch/DB/ResultSet.pm
  t/integration/04_test_datacenter_loaded.t
Labels: bug

#467 fix broken json schemas
  json-schema/input.yaml
  json-schema/response.yaml
  lib/Conch/Controller/Datacenter.pm
  lib/Conch/Controller/DatacenterRoom.pm
  lib/Conch/Model/WorkspaceRack.pm
  lib/Test/Conch.pm
  t/integration/crud/datacenter.t
  t/integration/crud/racks.t
Labels: bug

#472 fix missing pkeys
  lib/Conch/DB/Result/DatacenterRack.pm
  lib/Conch/DB/Result/DatacenterRoom.pm
  lib/Conch/DB/Result/UserWorkspaceRole.pm
  lib/Conch/DB/Result/Workspace.pm
  lib/Conch/DB/Result/WorkspaceDatacenterRack.pm
  lib/Conch/DB/Result/WorkspaceDatacenterRoom.pm
  lib/Test/ConchTmpDB.pm
  sql/migrations/0056-join-tables-primary-key.sql
  sql/schema.sql
Labels: database

#469 remove user creation from workspace invitation flow
  json-schema/input.yaml
  lib/Conch/Command/create_user.pm
  lib/Conch/Controller/User.pm
  lib/Conch/Controller/WorkspaceUser.pm
  lib/Conch/Mail.pm
  lib/Conch/Plugin/Mail.pm
  lib/Conch/Route/Workspace.pm
  t/integration/00_only_1_user_loaded.t
  t/integration/04_test_datacenter_loaded.t
Labels: needs-shell, needs-ui
