Repository joyent/conch-api, pull requests merged in 2018-02, with the labels that each got.

#148 feat: add a /version endpoint
  Conch/lib/Conch/Route.pm
  Conch/t/integration/00_only_1_user_loaded.t
  Conch/t/integration/01_hardware_products_loaded.t
  Conch/t/integration/02_hardware_product_profiles_loaded.t
  Conch/t/integration/03_zpool_profiles_loaded.t
  Conch/t/integration/04_test_datacenter_loaded.t
  Conch/t/integration/05_v1_schema.t
Labels: enhancement

#152 feat: introduce a singleton, called Conch::Pg, to hold our access to the database
  Conch/cpanfile
  Conch/cpanfile.snapshot
  Conch/lib/Conch.pm
  Conch/lib/Conch/Pg.pm
  Conch/lib/Conch/Plugin/Model.pm
Labels: enhancement

#154 fix: compare password hashes in constant time
  Conch/lib/Conch/Model/User.pm
  Conch/t/model/User.t
Labels: bug

#153 Mojo log adjustments
  Conch/lib/Conch.pm
  Conch/lib/Conch/Controller/DeviceReport.pm
Labels: enhancement

#158 Fix: Registering Relays
  Conch/lib/Conch/Controller/Relay.pm
  Conch/lib/Conch/Model/Relay.pm
  Conch/t/integration/00_only_1_user_loaded.t
  Conch/t/model/Relay.t
Labels: bug

#163 fix: change GET /version to be statically configurable
  Conch/conch.conf.dist
  Conch/lib/Conch/Route.pm
Labels: bug

#165 Revert "fix: change GET /version to be statically configurable"
  Conch/conch.conf.dist
  Conch/lib/Conch/Route.pm
Labels: bug

#168 fix: inviting a user to a workspace now functions
  Conch/lib/Conch/Controller/WorkspaceUser.pm
  Conch/lib/Conch/Plugin/Model.pm
Labels: api, bug

#172 fix: Conch::Error::Conflict is not used so remove it
  Conch/lib/Conch/Error/Conflict.pm
Labels: api

#173 tests: remove Mock::Quick usage in t/model/DeviceReport.t
  Conch/t/model/DeviceReport.t
Labels: api

#174 Some cleanups in Controller::User
  Conch/lib/Conch/Controller/User.pm
Labels: api

#178 chore: add NYTProf plugin
  Conch/conch.conf.dist
  Conch/cpanfile
  Conch/cpanfile.snapshot
  Conch/lib/Conch.pm
Labels: enhancement

#176 fix: use a simple formatter for converting PG timestamps
  Conch/cpanfile
  Conch/lib/Conch/Time.pm
  Conch/t/conch_time.t
Labels: api, enhancement
