Repository joyent/conch-api, pull requests merged in 2019-09, with the labels that each got.

#875 make device_setting and user_setting consistent: no nulls, strings only
  docs/modules/Conch::DB::Result::DeviceSetting.md
  docs/modules/Conch::DB::Result::UserSetting.md
  json-schema/request.yaml
  json-schema/response.yaml
  lib/Conch/Controller/DeviceSettings.pm
  lib/Conch/Controller/User.pm
  lib/Conch/DB/Result/DeviceSetting.pm
  lib/Conch/DB/Result/UserSetting.pm
  sql/migrations/0127-user-and-device_setting.sql
  sql/schema.sql
  t/integration/crud/devices.t
  t/integration/users.t
Labels: api, breaking, database, needs-shell

#876 better queries, most notably involving workspaces
  docs/modules/Conch::Command::check_workspace_racks.md
  docs/modules/Conch::DB::Result::Device.md
  docs/modules/Conch::DB::ResultSet::Device.md
  docs/modules/Conch::DB::ResultSet::Rack.md
  docs/modules/Conch::DB::ResultSet::UserWorkspaceRole.md
  docs/modules/Conch::DB::ResultSet::Workspace.md
  docs/modules/index.md
  lib/Conch/Command/check_layouts.pm
  lib/Conch/Command/check_workspace_racks.pm
  lib/Conch/Command/clean_roles.pm
  lib/Conch/Command/thin_device_reports.pm
  lib/Conch/Controller/Device.pm
  lib/Conch/Controller/DeviceReport.pm
  lib/Conch/Controller/DeviceSettings.pm
  lib/Conch/Controller/Rack.pm
  lib/Conch/Controller/User.pm
  lib/Conch/Controller/Workspace.pm
  lib/Conch/Controller/WorkspaceDevice.pm
  lib/Conch/Controller/WorkspaceRack.pm
  lib/Conch/Controller/WorkspaceRelay.pm
  lib/Conch/DB/Result/Device.pm
  lib/Conch/DB/ResultSet.pm
  lib/Conch/DB/ResultSet/Device.pm
  lib/Conch/DB/ResultSet/Rack.pm
  lib/Conch/DB/ResultSet/UserWorkspaceRole.pm
  lib/Conch/DB/ResultSet/Workspace.pm
  lib/Conch/Validation.pm
  t/integration/device-reports.t
  t/integration/users.t
  t/workspace-role.t
Labels: refactor, tests

#879 device report optimization
  docs/modules/Conch::DB::Result::DeviceReport.md
  lib/Conch/DB/Result/DeviceReport.pm
  sql/migrations/0114-device_report-drop-invalid.sql
  sql/schema.sql
Labels: database, device reports

#878 new endpoint for (re)defining a rack of layouts at once
  docs/modules/Conch::Controller::Rack.md
  docs/modules/Conch::Route::Rack.md
  json-schema/request.yaml
  lib/Conch/Controller/Rack.pm
  lib/Conch/Route/Rack.pm
  t/integration/crud/rack-layouts.t
Labels: api, enhancement

#881 hub.docker is no longer supported
  README.md
  docker/buildbot-release.bash
  docs/development.md
Labels: build, v2, v3

#880 v3: rollbar improvements
  conch.conf.dist
  cpanfile
  cpanfile.snapshot
  docs/modules/Conch::Plugin::Rollbar.md
  docs/modules/Test::Conch.md
  json-schema/other.yaml
  lib/Conch/Plugin/Logging.pm
  lib/Conch/Plugin/Rollbar.pm
  lib/Conch/Route.pm
  lib/Test/Conch.pm
  t/conch-log.t
  t/conch-rollbar.t
  t/database.t
  t/json-validation.t
Labels: enhancement, refactor, v3

#882 v3: moar docs!
  Makefile
  docs/index.md
  docs/json-schema/common.json
  docs/json-schema/device_report.json
  docs/json-schema/index.md
  docs/json-schema/other.json
  docs/json-schema/query_params.json
  docs/json-schema/request.json
  docs/json-schema/response.json
  docs/modules/Conch::DB::Result.md
  docs/modules/Conch::DB::ResultSet.md
  docs/modules/Conch::Route.md
  docs/modules/Conch::Route::Datacenter.md
  docs/modules/Conch::Route::DatacenterRoom.md
  docs/modules/Conch::Route::Device.md
  docs/modules/Conch::Route::DeviceReport.md
  docs/modules/Conch::Route::HardwareProduct.md
  docs/modules/Conch::Route::HardwareVendor.md
  docs/modules/Conch::Route::Organization.md
  docs/modules/Conch::Route::Rack.md
  docs/modules/Conch::Route::RackLayout.md
  docs/modules/Conch::Route::RackRole.md
  docs/modules/Conch::Route::Relay.md
  docs/modules/Conch::Route::User.md
  docs/modules/Conch::Route::Validation.md
  docs/modules/Conch::Route::Workspace.md
  docs/modules/index.md
  docs/scripts/index.md
  json-schema/common.yaml
  json-schema/device_report.yaml
  json-schema/other.yaml
  json-schema/query_params.yaml
  json-schema/request.yaml
  lib/Conch/DB/Result.pm
  lib/Conch/DB/ResultSet.pm
  lib/Conch/Route.pm
  lib/Conch/Route/Datacenter.pm
  lib/Conch/Route/DatacenterRoom.pm
  lib/Conch/Route/Device.pm
  lib/Conch/Route/DeviceReport.pm
  lib/Conch/Route/HardwareProduct.pm
  lib/Conch/Route/HardwareVendor.pm
  lib/Conch/Route/Organization.pm
  lib/Conch/Route/Rack.pm
  lib/Conch/Route/RackLayout.pm
  lib/Conch/Route/RackRole.pm
  lib/Conch/Route/Relay.pm
  lib/Conch/Route/User.pm
  lib/Conch/Route/Validation.pm
  lib/Conch/Route/Workspace.pm
  misc/pod2githubpages
Labels: api, docs

#883 v3: even moar docs
  bin/conch
  bin/conch-db
  docs/scripts/conch-db.md
  docs/scripts/conch.md
  misc/pod2githubpages
Labels: docs

#885 v3: more validation_result improvements
  docs/json-schema/response.json
  docs/modules/Conch::DB::Result::ValidationResult.md
  docs/modules/Conch::DB::Result::ValidationStateMember.md
  json-schema/response.yaml
  lib/Conch/Command/merge_validation_results.pm
  lib/Conch/Controller/DeviceValidation.pm
  lib/Conch/Controller/ValidationState.pm
  lib/Conch/DB/Result/ValidationResult.pm
  lib/Conch/DB/Result/ValidationStateMember.pm
  lib/Conch/Validation/CpuTemperature.pm
  lib/Conch/Validation/SwitchPeers.pm
  lib/Conch/ValidationSystem.pm
  sql/migrations/0129-validation_result-result_order.sql
  sql/migrations/0130-validation_result-cascade-delete.sql
  sql/schema.sql
  t/integration/device-reports.t
  t/integration/device-validations.t
  t/validation-system/run_validations.t
Labels: breaking, database, needs-shell, needs-ui, v3

#888 v3: a6 misc cleanup
  cpanfile
  cpanfile.snapshot
  docs/json-schema/README
  docs/json-schema/common.json
  docs/json-schema/device_report.json
  docs/json-schema/other.json
  docs/json-schema/query_params.json
  docs/json-schema/request.json
  docs/json-schema/response.json
  docs/modules/Conch::DB::Result::Device.md
  docs/modules/Conch::DB::ResultSet::Workspace.md
  docs/modules/README
  docs/modules/Test::Conch.md
  docs/scripts/README
  lib/Conch.pm
  lib/Conch/DB/Result/Device.pm
  lib/Conch/DB/ResultSet/Workspace.pm
  lib/Test/Conch.pm
  lib/Test/Conch/Fixtures.pm
  misc/pod2githubpages
  t/conch-log.t
  t/conch-status.t
  t/integration/crud/datacenter.t
  t/integration/crud/devices.t
  t/integration/crud/hardware-product.t
  t/integration/crud/organization.t
  t/integration/crud/rack-layouts.t
  t/integration/crud/rack-roles.t
  t/integration/crud/racks.t
  t/integration/crud/relay.t
  t/integration/crud/workspace-rack.t
  t/integration/crud/workspace.t
  t/integration/users.t
Labels: docs, tests

#889 v3: a6 small refactoring
  bin/conch-db
  docs/modules/Conch::Controller::WorkspaceRack.md
  lib/Conch/Controller/Organization.pm
  lib/Conch/Controller/WorkspaceOrganization.pm
  lib/Conch/Controller/WorkspaceRack.pm
  lib/Conch/Plugin/Database.pm
  lib/Conch/Plugin/Logging.pm
  lib/Conch/Route/Workspace.pm
  misc/get-api-token
  t/conch-log.t
  t/integration/crud/organization.t
  t/integration/crud/workspace-rack.t
Labels: api, enhancement, refactor

#890 v3: builds
  docs/json-schema/request.json
  docs/json-schema/response.json
  docs/modules/Conch::Controller::Build.md
  docs/modules/Conch::Controller::User.md
  docs/modules/Conch::DB::Result::Build.md
  docs/modules/Conch::DB::Result::Device.md
  docs/modules/Conch::DB::Result::Organization.md
  docs/modules/Conch::DB::Result::OrganizationBuildRole.md
  docs/modules/Conch::DB::Result::Rack.md
  docs/modules/Conch::DB::Result::UserAccount.md
  docs/modules/Conch::DB::Result::UserBuildRole.md
  docs/modules/Conch::DB::ResultSet::Build.md
  docs/modules/Conch::DB::ResultSet::Device.md
  docs/modules/Conch::Route::Build.md
  docs/modules/index.md
  json-schema/request.yaml
  json-schema/response.yaml
  lib/Conch/Controller/Build.pm
  lib/Conch/Controller/User.pm
  lib/Conch/DB/Helper/ResultSet/WithRole.pm
  lib/Conch/DB/Result/Build.pm
  lib/Conch/DB/Result/Device.pm
  lib/Conch/DB/Result/Organization.pm
  lib/Conch/DB/Result/OrganizationBuildRole.pm
  lib/Conch/DB/Result/Rack.pm
  lib/Conch/DB/Result/UserAccount.pm
  lib/Conch/DB/Result/UserBuildRole.pm
  lib/Conch/DB/ResultSet/Build.pm
  lib/Conch/DB/ResultSet/Device.pm
  lib/Conch/DB/ResultSet/Rack.pm
  lib/Conch/DB/ResultSet/Workspace.pm
  lib/Conch/Route.pm
  lib/Conch/Route/Build.pm
  lib/Test/Conch/Fixtures.pm
  schema-loader.yaml
  sql/migrations/0131-builds.sql
  sql/schema.sql
  t/build-role.t
  t/integration/crud/build.t
  t/integration/crud/devices.t
  t/integration/crud/racks.t
  t/workspace-role.t
  templates/email/build_organization_add_admins.txt.ep
  templates/email/build_organization_add_members.txt.ep
  templates/email/build_organization_remove_admins.txt.ep
  templates/email/build_organization_remove_members.txt.ep
  templates/email/build_organization_update_admins.txt.ep
  templates/email/build_organization_update_members.txt.ep
  templates/email/build_user_add_admins.txt.ep
  templates/email/build_user_add_user.txt.ep
  templates/email/build_user_remove_admins.txt.ep
  templates/email/build_user_remove_user.txt.ep
  templates/email/build_user_update_admins.txt.ep
  templates/email/build_user_update_user.txt.ep
Labels: api, breaking, needs-shell, needs-ui, v3

#891 v3: small fixes
  CODEOWNERS
  bin/conch-db
  docs/json-schema/other.json
  docs/modules/Conch::Command::merge_validation_results.md
  json-schema/other.yaml
  lib/Conch.pm
  lib/Conch/Command/merge_validation_results.pm
  lib/Conch/Command/thin_device_reports.pm
  lib/Conch/Controller/DeviceInterface.pm
  lib/Conch/Controller/DeviceLocation.pm
  lib/Conch/Controller/HardwareProduct.pm
  lib/Conch/Controller/RackLayout.pm
  lib/Conch/Controller/WorkspaceDevice.pm
  lib/Conch/DB/ResultSet/DeviceReport.pm
  lib/Conch/DB/ResultSet/UserAccount.pm
  lib/Conch/Time.pm
  lib/Conch/UUID.pm
  lib/Test/Conch.pm
  lib/Test/Conch/Fixtures.pm
  misc/get-api-token
  misc/pod2githubpages
  t/integration/crud/devices.t
  t/integration/crud/workspace-rack.t
  t/integration/device-validations.t
  t/lib/Conch/Validation/TestConchValidationTester.pm
  t/validation-system/check_validations.t
  t/validation-system/exceptions.t
  t/validation-system/load_validations.t
  t/validation-system/update-validation-plans.t
Labels: bug, tests, wat

#895 add a X-Conch-API header to every response
  lib/Conch.pm
  t/integration/crud/unsecured-endpoints.t
Labels: api, bug, needs-shell, needs-ui

#894 add a X-Conch-API header to every response; skip version check for GET /version
  lib/Conch.pm
  lib/Conch/Plugin/ClientVerification.pm
  t/client-verification.t
  t/integration/unsecured-endpoints.t
Labels: api, bug, needs-shell, needs-ui
