Repository joyent/conch-api, pull requests merged in 2019-03, with the labels that each got.

#674 fixes for 2.24
  cpanfile
  json-schema/response.yaml
  lib/Conch/Command/insert_validation_states.pm
  lib/Conch/Controller/DeviceReport.pm
  lib/Conch/Controller/Validation.pm
  lib/Conch/DB/Result/Validation.pm
Labels: api, bug, device reports

#675 remove the image removal part of the buildbot process
  docker/buildbot-prerelease.bash
  docker/buildbot-release.bash
Labels: build

#678 make datacenter_room.alias not-nullable
  json-schema/input.yaml
  json-schema/response.yaml
  lib/Conch/DB/Result/DatacenterRoom.pm
  lib/Test/Conch/Fixtures.pm
  sql/migrations/0078-datacenter_room-alias.sql
  sql/schema.sql
  t/integration/04_test_datacenter_loaded.t
  t/integration/crud/rooms.t
Labels: database, needs-shell

#681 only count populated DIMM slots in DimmCount validation
  lib/Conch/Command/update_validations_release_224.pm
  lib/Conch/Validation/DimmCount.pm
  t/validations/dimm_count_v1.t
Labels: bug, validation

#682 make device_nic device_id + iface_name unique
  lib/Conch/Controller/DeviceReport.pm
  sql/migrations/0079-device_nic-iface_name.sql
  sql/schema.sql
Labels: database

#684 more 2.24.4 fixes
  lib/Conch/Command/thin_device_reports.pm
  lib/Conch/Command/update_validations_release_224.pm
  lib/Conch/Controller/DeviceReport.pm
Labels: device reports

#687 after processing device reports, include results with the validation state
  lib/Conch/Controller/DeviceReport.pm
  t/integration/04_test_datacenter_loaded.t
  t/integration/crud/devices.t
Labels: api, enhancement

#683 Device pxe endpoints
  json-schema/response.yaml
  lib/Conch/Controller/Device.pm
  lib/Conch/Controller/WorkspaceDevice.pm
  lib/Conch/DB/ResultSet.pm
  lib/Conch/DB/ResultSet/DeviceNic.pm
  lib/Conch/Route/Device.pm
  lib/Conch/Route/Workspace.pm
  t/integration/04_test_datacenter_loaded.t
  t/integration/crud/devices.t
  t/integration/crud/workspace-devices.t
  t/pod-spelling.t
Labels: api, enhancement

#689 disk hba, enclosure fields are sometimes numeric in device report payloads
  json-schema/input.yaml
  t/integration/resource/passing-device-report.json
Labels: bug, device reports

#690 handle mac+iface_name combinations changing
  lib/Conch/Controller/DeviceReport.pm
  t/integration/04_test_datacenter_loaded.t
Labels: bug, device reports

#691 fix LinksUp validation
  lib/Conch/Command/update_validations_release_225.pm
  lib/Conch/Validation/LinksUp.pm
  t/validations/links_up_v1.t
Labels: bug, validation, wat

#688 new endpoint: GET /validation_state/:id
  lib/Conch/Controller/ValidationState.pm
  lib/Conch/Route/Validation.pm
  t/integration/crud/devices.t
Labels: api, enhancement

#692 get rooms out of workspaces
  bin/conch-db
  docs/validation/BaseValidation.md
  docs/validation/TestingValidations.md
  json-schema/input.yaml
  json-schema/response.yaml
  lib/Conch/Command/check_layouts.pm
  lib/Conch/Controller/DatacenterRoom.pm
  lib/Conch/Controller/Device.pm
  lib/Conch/Controller/Rack.pm
  lib/Conch/Controller/RackLayout.pm
  lib/Conch/Controller/RackRole.pm
  lib/Conch/Controller/WorkspaceDevice.pm
  lib/Conch/Controller/WorkspaceRack.pm
  lib/Conch/Controller/WorkspaceRelay.pm
  lib/Conch/Controller/WorkspaceRoom.pm
  lib/Conch/DB/Result/DatacenterRoom.pm
  lib/Conch/DB/Result/DeviceLocation.pm
  lib/Conch/DB/Result/HardwareProduct.pm
  lib/Conch/DB/Result/Rack.pm
  lib/Conch/DB/Result/RackLayout.pm
  lib/Conch/DB/Result/RackRole.pm
  lib/Conch/DB/Result/Workspace.pm
  lib/Conch/DB/Result/WorkspaceDatacenterRack.pm
  lib/Conch/DB/Result/WorkspaceRack.pm
  lib/Conch/DB/ResultSet/Device.pm
  lib/Conch/DB/ResultSet/DeviceLocation.pm
  lib/Conch/DB/ResultSet/Rack.pm
  lib/Conch/DB/ResultSet/Workspace.pm
  lib/Conch/DB/Util.pm
  lib/Conch/Route/Datacenter.pm
  lib/Conch/Route/Workspace.pm
  lib/Conch/Validation.pm
  lib/Conch/Validation/DeviceProductName.pm
  lib/Conch/Validation/SwitchPeers.pm
  lib/Test/Conch.pm
  lib/Test/Conch/Fixtures.pm
  lib/Test/Conch/Validation.pm
  schema-loader.yaml
  sql/migrations/0080-datacenter_rack-rename.sql
  sql/migrations/0081-workspace_rack-cascade-delete.sql
  sql/migrations/0082-no-workspace-rooms.sql
  sql/migrations/0083-racks-not-deactivatable.sql
  sql/schema.sql
  t/fixtures.t
  t/integration/00_only_1_user_loaded.t
  t/integration/04_test_datacenter_loaded.t
  t/integration/crud/devices.t
  t/integration/crud/rack_layouts.t
  t/integration/crud/rack_roles.t
  t/integration/crud/racks.t
  t/integration/crud/relay.t
  t/integration/crud/removed-endpoints.t
  t/integration/crud/rooms.t
  t/integration/crud/unsecured-endpoints.t
  t/integration/crud/workspace-devices.t
  t/integration/crud/workspace-rack.t
  t/lib/Conch/Validation/TestConchValidationTester.pm
  t/validation-system/test-conch-validation.t
  t/validations/switch_peers_v1.t
Labels: api, database, enhancement, needs-shell, needs-ui

#693 more housekeeping
  json-schema/response.yaml
  lib/Conch/Controller/Device.pm
  lib/Conch/Controller/Schema.pm
  lib/Conch/Controller/ValidationPlan.pm
  lib/Conch/DB/Deactivatable.pm
  lib/Conch/DB/Result/Device.pm
  lib/Conch/DB/Result/DeviceDisk.pm
  lib/Conch/DB/Result/DeviceMemory.pm
  lib/Conch/DB/ResultSet/DeviceReport.pm
  lib/Conch/Plugin/JsonValidator.pm
  lib/Conch/Route/Validation.pm
  lib/Conch/Validation.pm
  sql/migrations/0084-device_disk-hba.sql
  sql/migrations/0085-device_memory.sql
  sql/schema.sql
  t/integration/crud/devices.t
Labels: api, database, refactor

#696 allow system admins to access all devices
  lib/Conch/Controller/Device.pm
  lib/Test/Conch.pm
  lib/Test/Conch/Fixtures.pm
  t/integration/crud/devices.t
Labels: enhancement, wat

#701 skip creating the conch database when initializing the db
  lib/Conch/DB/Util.pm
  lib/Test/Conch.pm
Labels: database, docker

#700 avoid the use of a tempdir when running external commands
  cpanfile
  cpanfile.snapshot
  lib/Conch/Plugin/GitVersion.pm
  t/git-version.t
Labels: docker

#702 Support docker-compose
  .gitignore
  Dockerfile
  Dockerfile.dev
  README.md
  conch.conf.dist
  docker-compose.yml
Labels: docker

#703 new enums
  json-schema/response.yaml
  lib/Conch/Controller/DeviceReport.pm
  lib/Conch/Controller/Rack.pm
  lib/Conch/Controller/WorkspaceDevice.pm
  lib/Conch/Controller/WorkspaceRack.pm
  lib/Conch/DB/Result/Device.pm
  lib/Conch/DB/ResultSet/DeviceLocation.pm
  lib/Test/Conch/Fixtures.pm
  sql/migrations/0087-device-health-enum.sql
  sql/schema.sql
  t/integration/04_test_datacenter_loaded.t
  t/integration/crud/devices.t
  t/integration/crud/rack_layouts.t
  t/integration/crud/unsecured-endpoints.t
  t/integration/crud/workspace-devices.t
  t/lib/Conch/Validation/TestConchValidationTester.pm
Labels: database

#706 Handle 'role' existing in the POST /rack/:id payload when there is no change
  json-schema/input.yaml
  lib/Conch/Controller/Rack.pm
  t/integration/crud/racks.t
Labels: api, bug

#708 send the same password to the user that we stored in their db record
  lib/Conch/Controller/User.pm
Labels: api, bug, high priority, wat

#705 misc fixes for 2.26
  bin/conch-db
  cpanfile
  cpanfile.snapshot
  json-schema/input.yaml
  json-schema/response.yaml
  lib/Conch.pm
  lib/Conch/Controller/Datacenter.pm
  lib/Conch/Controller/DatacenterRoom.pm
  lib/Conch/Controller/Device.pm
  lib/Conch/Controller/DeviceInterface.pm
  lib/Conch/Controller/DeviceReport.pm
  lib/Conch/Controller/DeviceSettings.pm
  lib/Conch/Controller/DeviceValidation.pm
  lib/Conch/Controller/HardwareProduct.pm
  lib/Conch/Controller/HardwareVendor.pm
  lib/Conch/Controller/Login.pm
  lib/Conch/Controller/Rack.pm
  lib/Conch/Controller/RackLayout.pm
  lib/Conch/Controller/RackRole.pm
  lib/Conch/Controller/Relay.pm
  lib/Conch/Controller/Schema.pm
  lib/Conch/Controller/User.pm
  lib/Conch/Controller/Validation.pm
  lib/Conch/Controller/ValidationPlan.pm
  lib/Conch/Controller/ValidationState.pm
  lib/Conch/Controller/WorkspaceRack.pm
  lib/Conch/Controller/WorkspaceUser.pm
  lib/Conch/Route.pm
  lib/Test/Conch.pm
  t/integration/00_only_1_user_loaded.t
  t/integration/04_test_datacenter_loaded.t
  t/integration/06_secured_endpoints.t
  t/integration/crud/devices.t
  t/integration/crud/hardware_vendor.t
  t/integration/crud/workspace-rack.t
  t/schema.t
Labels: api, bug, device reports

#709 new endpoint: GET /device_report/:id
  json-schema/response.yaml
  lib/Conch/Controller/DeviceReport.pm
  lib/Conch/DB/Result/DeviceReport.pm
  lib/Conch/Route.pm
  lib/Conch/Route/DeviceReport.pm
  t/integration/04_test_datacenter_loaded.t
  t/integration/crud/devices.t
Labels: api, enhancement

#711 provide more detailed device location information in GET /device/:id
  json-schema/response.yaml
  lib/Conch/Controller/Device.pm
  lib/Conch/Controller/DeviceLocation.pm
  lib/Conch/DB/ResultSet/DeviceLocation.pm
  t/integration/crud/devices.t
Labels: api, breaking, needs-shell, needs-ui

#712 clean up some of the vendor names in the tests
  lib/Test/Conch/Fixtures.pm
  t/integration/crud/unsecured-endpoints.t
Labels: tests
