Repository joyent/conch-api, pull requests merged in 2019-02, with the labels that each got.

#634 Fix DIMMCount and CPUCount
  json-schema/input.yaml
  lib/Conch/Command/update_validations_release_223.pm
  lib/Conch/Validation/CpuCount.pm
  lib/Conch/Validation/DimmCount.pm
  lib/Conch/Validation/RamTotal.pm
  t/validations/cpu_count_v1.t
  t/validations/dimm_count_v1.t
  t/validations/ram_total_v1.t
Labels: device reports, refactor, validation

#636 add "Reviewed By" line(s) in ghch
  misc/ghch
Labels: enhancement

#633 DB config and connection improvements
  conch.conf.dist
  lib/Conch.pm
  lib/Conch/Pg.pm
  lib/Conch/Plugin/AuthHelpers.pm
  lib/Conch/Plugin/Database.pm
  lib/Conch/Plugin/GitVersion.pm
  lib/Conch/Plugin/JsonValidator.pm
  lib/Conch/Plugin/Logging.pm
  lib/Conch/Plugin/Rollbar.pm
  lib/Test/Conch.pm
  t/database.t
Labels: WIP, database, enhancement, needs-buildops_infra, refactor

#639 fix bad report id reference
  lib/Conch/Controller/DeviceReport.pm
Labels: bug, high priority

#638 fix sanity row count check in update script
  lib/Conch/Command/update_validations_release_223.pm
Labels: database, validation

#637 improvements for validation testing infrastructure, documentation
  Makefile
  cpanfile
  cpanfile.snapshot
  docs/validation/BaseValidation.md
  docs/validation/TestingValidations.md
  lib/Conch/Validation.pm
  lib/Conch/Validation/SwitchPeers.pm
  lib/Test/Conch.pm
  lib/Test/Conch/Fixtures.pm
  lib/Test/Conch/Validation.pm
  misc/validate
  t/fixtures.t
  t/lib/Conch/Validation/TestConchValidationTester.pm
  t/pod-spelling.t
  t/validation-system/test-conch-validation.t
  t/validations/00_base_class.t
  t/validations/bios_firmware_version_v1.t
  t/validations/cpu_count_v1.t
  t/validations/cpu_temperature_v1.t
  t/validations/dimm_count_v1.t
  t/validations/nvme_ssd_num_v1.t
  t/validations/raid_lun_num_v1.t
  t/validations/ram_total_v1.t
  t/validations/sas_hdd_num_v1.t
  t/validations/sas_ssd_num_v1.t
  t/validations/sata_hdd_num_v1.t
  t/validations/sata_ssd_num_v1.t
  t/validations/slog_slot_v1.t
  t/validations/switch_peers_v1.t
  t/validations/usb_hdd_num_v1.t
Labels: enhancement, refactor, validation

#646 fix workspace-rack query
  lib/Conch/Controller/WorkspaceRack.pm
  t/integration/04_test_datacenter_loaded.t
  t/integration/crud/workspace-rack.t
Labels: api, bug, wat

#647 add ?validated=T|F option to GET /workspace/:id/device
  lib/Conch/Controller/WorkspaceDevice.pm
  t/integration/04_test_datacenter_loaded.t
Labels: api, enhancement

#648 add rack_id, rack_unit_start to 'Device' json schema
  json-schema/response.yaml
  lib/Conch/Controller/Device.pm
  lib/Conch/Controller/WorkspaceDevice.pm
  lib/Conch/Controller/WorkspaceRack.pm
  lib/Conch/Controller/WorkspaceRelay.pm
  lib/Conch/DB/Result/Device.pm
  t/integration/04_test_datacenter_loaded.t
Labels: api, enhancement

#641 Cut validations over to DBIC
  cpanfile
  docs/validation/BaseValidation.md
  docs/validation/Guide.md
  docs/validation/TestingValidations.md
  lib/Conch/Models.pm
  lib/Conch/Validation.pm
  lib/Conch/Validation/BiosFirmwareVersion.pm
  lib/Conch/Validation/CpuCount.pm
  lib/Conch/Validation/CpuTemperature.pm
  lib/Conch/Validation/DeviceProductName.pm
  lib/Conch/Validation/DimmCount.pm
  lib/Conch/Validation/DimmMap.pm
  lib/Conch/Validation/DiskSmartStatus.pm
  lib/Conch/Validation/DiskTemperature.pm
  lib/Conch/Validation/FirmwareCurrent.pm
  lib/Conch/Validation/LinksUp.pm
  lib/Conch/Validation/NicsNum.pm
  lib/Conch/Validation/NvmeSsdNum.pm
  lib/Conch/Validation/RaidLunNum.pm
  lib/Conch/Validation/RamTotal.pm
  lib/Conch/Validation/SasHddNum.pm
  lib/Conch/Validation/SasSsdNum.pm
  lib/Conch/Validation/SataHddNum.pm
  lib/Conch/Validation/SataSsdNum.pm
  lib/Conch/Validation/SlogSlot.pm
  lib/Conch/Validation/SwitchPeers.pm
  lib/Conch/Validation/UsbHddNum.pm
  lib/Conch/ValidationSystem.pm
  lib/Test/Conch.pm
  lib/Test/Conch/Validation.pm
  t/lib/Conch/Validation/ExternalException.pm
  t/lib/Conch/Validation/LocalException.pm
  t/lib/Conch/Validation/MutateDevice.pm
  t/lib/Conch/Validation/TestConchValidationTester.pm
  t/validation-system/check_validations.t
  t/validation-system/exceptions.t
  t/validation-system/load_validations.t
  t/validation-system/run_validations.t
  t/validation-system/test-conch-validation.t
  t/validations/00_base_class.t
Labels: refactor, validation

#651 final removal of legacy database code
  cpanfile
  cpanfile.snapshot
  lib/Conch.pm
  lib/Conch/Class/DatacenterRack.pm
  lib/Conch/Class/DatacenterRoom.pm
  lib/Conch/Class/DeviceLocation.pm
  lib/Conch/Class/HardwareProduct.pm
  lib/Conch/Class/HardwareProductProfile.pm
  lib/Conch/Class/ZpoolProfile.pm
  lib/Conch/Model/Device.pm
  lib/Conch/Model/DeviceLocation.pm
  lib/Conch/Model/HardwareProduct.pm
  lib/Conch/Models.pm
  lib/Conch/Pg.pm
  lib/Conch/Plugin/Database.pm
  lib/Test/Conch.pm
  lib/Test/Conch/Fixtures.pm
  lib/Test/ConchTmpDB.pm
  t/class/DatacenterRack.t
  t/class/DatacenterRoom.t
  t/database.t
  t/integration/00_only_1_user_loaded.t
  t/model/Device.t
  t/model/DeviceLocation.t
  t/model/HardwareProduct.t
  t/validation-system/run_validations.t
Labels: database, refactor, wat

#655 when building a release in docker, use --no-cache
  docker/buildbot-release.bash
Labels: build, docker

#653 device report retention changes
  cpanfile
  cpanfile.snapshot
  lib/Conch/Command/thin_device_reports.pm
  lib/Conch/Controller/DeviceReport.pm
  lib/Conch/DB/Result/DeviceReport.pm
  lib/Conch/DB/Result/ValidationResult.pm
  lib/Conch/DB/Result/ValidationState.pm
  lib/Conch/DB/Result/ValidationStateMember.pm
  lib/Conch/DB/ResultSet.pm
  lib/Conch/DB/ResultSet/DeviceReport.pm
  lib/Conch/ValidationSystem.pm
  sql/migrations/0074-device_report-cascade-delete.sql
  sql/migrations/0075-validation_status_enum.sql
  sql/migrations/0076-device_report-retain.sql
  sql/schema.sql
  t/integration/04_test_datacenter_loaded.t
Labels: database, enhancement, validation

#657 remove all traces of zpool_profile
  json-schema/input.yaml
  json-schema/response.yaml
  lib/Conch/Controller/HardwareProduct.pm
  lib/Conch/DB/Result/HardwareProduct.pm
  lib/Conch/DB/Result/HardwareProductProfile.pm
  lib/Conch/DB/Result/ZpoolProfile.pm
  lib/Test/Conch/Fixtures.pm
  schema-loader.yaml
  sql/migrations/0077-drop-zpool_profile.sql
  sql/schema.sql
  t/integration/02_hardware_product_profiles_loaded.t
  t/integration/03_zpool_profiles_loaded.t
  t/integration/crud/hardware_product.t
  t/pod-spelling.t
Labels: api, database

#658 misc fixes for 2.24
  json-schema/response.yaml
  lib/Conch/Command/check_layouts.pm
  lib/Conch/Command/clean_permissions.pm
  lib/Conch/Command/update_validation_states.pm
  lib/Conch/Command/update_validations.pm
  lib/Conch/Command/update_validations_release_223.pm
  lib/Conch/Command/workspaces.pm
  lib/Conch/Controller/Datacenter.pm
  lib/Conch/Controller/Device.pm
  lib/Conch/Controller/DeviceReport.pm
  lib/Conch/Controller/DeviceValidation.pm
  lib/Conch/Controller/HardwareProduct.pm
  lib/Conch/Controller/User.pm
  lib/Conch/Controller/WorkspaceDevice.pm
  lib/Conch/Controller/WorkspaceRack.pm
  lib/Conch/DB/ResultSet/UserAccount.pm
  lib/Conch/DB/ResultSet/Workspace.pm
  lib/Conch/DB/ResultsExist.pm
  lib/Conch/Plugin/Database.pm
  lib/Conch/Plugin/Logging.pm
  lib/Test/Conch.pm
  lib/Test/Conch/Fixtures.pm
  misc/ghch
  t/integration/crud/unsecured-endpoints.t
Labels: bug, docs

#659 command-line functionality to initialize the database and run migrations
  bin/conch-db
  lib/Conch/DB/Util.pm
  lib/Conch/Plugin/Database.pm
  lib/Test/Conch.pm
  t/database.t
Labels: database, docker

#662 new /datacenter_rack/:id/assignment endpoints, for device-rack associations
  json-schema/input.yaml
  json-schema/response.yaml
  lib/Conch/Controller/DatacenterRack.pm
  lib/Conch/DB/ResultSet/DatacenterRack.pm
  lib/Conch/Route/Datacenter.pm
  lib/Test/Conch/Fixtures.pm
  t/integration/crud/racks.t
Labels: api, enhancement

#667 fixes for 2.24
  docs/development.md
  json-schema/input.yaml
  json-schema/response.yaml
  lib/Conch/Controller/Datacenter.pm
  lib/Conch/Controller/DatacenterRack.pm
  lib/Conch/Controller/DatacenterRackRole.pm
  lib/Conch/Controller/DatacenterRoom.pm
  lib/Conch/Controller/Device.pm
  lib/Conch/Controller/User.pm
  lib/Conch/Controller/WorkspaceRack.pm
  lib/Conch/Plugin/JsonValidator.pm
  misc/validate
  t/conch_time.t
  t/integration/00_only_1_user_loaded.t
  t/integration/04_test_datacenter_loaded.t
  t/integration/crud/datacenter.t
  t/integration/crud/devices.t
  t/integration/crud/rack_roles.t
  t/integration/crud/racks.t
  t/integration/crud/rooms.t
Labels: api, bug, database, enhancement, needs-shell

#670 allow setting a device asset_tag to null
  json-schema/input.yaml
  lib/Conch/Controller/Device.pm
  lib/Test/Conch.pm
  t/integration/04_test_datacenter_loaded.t
  t/integration/crud/devices.t
Labels: api, bug, needs-shell

#669 populate validation_state rows from old device_validate backup
  lib/Conch/Command/insert_validation_states.pm
Labels: database, device reports

#671 only send a ROLLBACK if the connection is still open
  lib/Conch/Plugin/Database.pm
Labels: bug, database
